name: JIRA Configuration
description: 'Auswertung der Issues eines Repositories seit dem letzten Tag, Bereitstellen von Issue-Infos f端r eventuelle Release-Notes, Erzeugen einer neuen Version f端r ein nachfolgendes Releasebuild'
inputs:
  jiraUrl:
    description: Organisationsinterne URL des angebundenen JIRA-Systems
    required: true
  jiraUrl2:
    description: Organisationsinterne URL des angebundenen JIRA-Systems , hier des Component-Version-Plugins
    required: true
  jiraCredentials:
    description: Organisationsinterne Credentials (user:password) des angebundenen JIRA-Systems
    required: true
  jiraProject:
    description: der Name des zu bedienenden JIRA-Projekts
    required: true
  component:
    description: der Name der zu erzeugenden Komponente (erforderlich f端r Auswertung der Komponenten)
    required: true
  componentVersion:
    description: die neu einzurichtende Version
    required: true
  componentList:
    description: Liste der Komponenten, f端r die eine Component-Version erzeugt werden soll
    required: true
  atlassianToolsVersion:
    description: die Version der organisationsinternen AtlassianDeveloperTools (separates Repository)
    required: true

runs:
  using: "composite"
  steps: 
    - id: jiraConfig
      shell: bash
      run: |
        echo "Erzeugen der Versionen in Jira"
        echo "${{ inputs.component }}"
        echo "${{ inputs.componentVersion }}"
        atlassianToolsDir=./mcbscore/github/atlassian-tools

        java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-info.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{ inputs.atlassianToolsVersion }}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          jira_config.CreateVersionKt \ 
          "${{ inputs.jiraUrl }}" \
          "${{ inputs.jiraUrl2 }}" \
          "${{ inputs.jiraCredentials }}" \
          "${{ inputs.component }}"_"${{ inputs.componentVersion }}" \
          "${{ inputs.jiraProject }}" \
          "${{ inputs.componentList }}"