name: Fetch Default-Epic
description: 'Bereitstellen des Default-Epic im Environment'
inputs:
  

runs:
  using: "composite"
  steps: 
    - id: fetchDefaultEpic
      shell: bash
      run: |
        echo fetch Defasult-Epic ...
        echo "DEFAULTEPIC=${{ vars.DEFAULTEPIC }}"
          
        echo "DEFAULTEPIC=${{ vars.DEFAULTEPIC }}" >> $GITHUB_ENV
    
