name: Upload Release Asset
description: Aktion zum Hochladen von GitHub-Release-Asset

inputs:
  releaseId:
    description: Die ID des Releases, zu dem die Asset hinzugefügt werden sollen.
    required: true
  assetName:
    description: Der Name des Asset, das hochgeladen werden soll.
    required: true
  assetPath:
    description: Der Pfad zum Asset, das hochgeladen werden soll.
    required: true
  assetContentType:
    description: Der Inhaltstyp des Assets, das hochgeladen werden soll.
    required: false
    default: application/octet-stream

outputs:
  id:
    description: Die ID des hochgeladenen Asset.
    value: ${{ steps.upload-release-asset.outputs.id }}
  browserDownloadUrl:
    description:  Die URL zum Herunterladen des Asset.
    value: ${{ steps.upload-release-asset.outputs.browserDownloadUrl }}

runs:
  using: "composite"
  steps:
    - id: upload-release-asset
      shell: bash
      run: |
       resultJson=`
        gh api \
          --method POST \
          -H "Accept: application/vnd.github+json" \
          -H "Content-Type: ${{ inputs.assetContentType }}" \ 
          /repos/${{ github.repository }}/releases/${{ inputs.releaseId }}/assets?name=${{ inputs.assetName }} \
          -f '${{ inputs.assetPath }}'`
        
        outVarId=`jq -r .id <<< "$resultJson"`
        echo "id=$outVarId" >> $GITHUB_OUTPUT
        outVarBrowserDownloadUrl=`jq -r .browser_download_url <<< "$resultJson"`
        echo "browserDownloadUrl=$outVarBrowserDownloadUrl" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ env.TOKEN }}
