name: DEV Deployment
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: DEV Deployment ${{ github.event.inputs.componentVersion }}

on:
  workflow_dispatch:
    inputs:
      additionalDeploymentComponent:
        description: Ermöglicht Deployment unter anderem Namen
        required: false
      componentVersion:
        description: Die Version der Komponente
        required: true
      platforms:
        description: Die Zielserver-Plattform(en)
        type: choice
        options: [ "vm, k8s", "vm", "k8s" ]
        required: false
        default: "vm, k8s"
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main
      deploymentRepositoryBranch:
        description: Branch von Repository ms-deployment, der benutzt werden soll
        required: false
        default: main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      # Workflow Properties einlesen
      - name: Read workflow.properties
        shell: bash
        run: |
          cat ./.github/workflow.properties >> $GITHUB_ENV

      # Starte Deployment auf DEV
      - name: Invoke deployment workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deployment
          token: ${{ env.TOKEN }}
          inputs: >
            {
              "component": "${{ env.COMPONENT }}",
              "componentVersion": "${{ inputs.componentVersion }}",
              "environment": "dev",
              "platforms": "${{ inputs.platforms }}",
              "additionalDeploymentComponent": "${{ inputs.additionalDeploymentComponent }}",
              "actionsRepositoryBranch": "${{ inputs.actionsRepositoryBranch }}",
              "deploymentRepositoryBranch": "${{ inputs.deploymentRepositoryBranch }}"
            }

      # Starte Developer Portal Upload
      - name: Invoke developer portal upload workflow
        if: ${{ hashFiles('**/developerPortal.yml') != '' && github.event.inputs.additionalDeploymentComponent == '' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: DeveloperPortal Upload
          token: ${{ env.TOKEN }}
          inputs: >
            {
              "component": "${{ env.COMPONENT }}",
              "environment": "dev",
              "componentVersion": "${{ github.event.inputs.componentVersion }}",
              "actionsRepositoryBranch": "${{ github.event.inputs.actionsRepositoryBranch }}"
            }