name: Deployment

on:
  workflow_dispatch:
    inputs:
      component:
        description: Der Name der Komponente
        required: true
      componentVersion:
        description: Die Version der Komponente
        required: true
      additionalDeploymentComponent:
        description: Ermöglicht Deployment unter anderem Namen
        required: false
      environment:
        description: Die Zielumgebung
        required: true
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        type: string
        required: false
        default: main
      deploymentRepositoryBranch:
        description: Branch von Repository ms-deployment, der benutzt werden soll
        required: false
        default: main
      bambiNotification:
        description: Bambi Notification?
        type: boolean
        required: false
        default: false

jobs:
  create-deployment:
    runs-on: ubuntu-latest

    steps:
      # Secrets aus AWS auslesen
      - name: Read and set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Read AWS Parameters
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      # DEPLOYMENT_REF Umgebungsvariable setzen
      - name: Determine deployment ref
        shell: bash
        run: |
          if  [[ ${{ github.event.inputs.componentVersion }} =~ '-SNAPSHOT' ]] ;
          then
            echo "DEPLOYMENT_REF=develop" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_REF=${{ github.event.inputs.componentVersion }}" >> $GITHUB_ENV
          fi

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: create-deployment
        with:
          token: ${{ env.TOKEN }}
          environment: ${{ github.event.inputs.environment }}
          ref: ${{ env.DEPLOYMENT_REF }}

    outputs:
      deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}

  deploy:
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, vm]
    needs: create-deployment
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github
      DEPLOYMENT_PATH: mcbscore/deployment
      NODEJS_VERSION: 16

    steps:
      # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
      - name: Change Owner to Runner User
        if: ${{ always() }}
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
          docker run --rm -v `pwd`:/target -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

      # Leeren Workspace sicherstellen
      - name: Ensure clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf *

      # Repository auschecken unter $GITHUB_WORKSPACE
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/deployment_user = DEPLOYMENT_USER,
            /github/secrets/checkmk_user = CHECKMK_USER, 
            /github/secrets/checkmk_password = CHECKMK_PW

      # Die internen Actions auschecken
      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ inputs.actionsRepositoryBranch }}

      # Auschecken des Deployment Repositories
      - name: Checkout Deployment Data / Scripts
        uses: actions/checkout@v3
        with:
          repository: freenet-group/ms-deployment
          token: ${{ env.TOKEN }}
          path: ${{ env.DEPLOYMENT_PATH }}
          ref: ${{ github.event.inputs.deploymentRepositoryBranch }}

      # ##################################################################################
      # Initialize Workflow
      # ##################################################################################

      - id: init-workflow
        name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installNodeJs: true
          installJq: true

      - name: Download Release
        id: downloadRelease
        uses: ./mcbscore/github/actions/download-release-assets-action
        with:
          version: ${{ github.event.inputs.componentVersion }}
          assetPattern: '-${{ github.event.inputs.componentVersion }}.jar'
          targetPath: './${{ env.DEPLOYMENT_PATH }}/release'
          token: ${{ env.TOKEN }}

      # Standard Deployment
      - name: Deployment
        id: deployRelease
        if: ${{ github.event.inputs.additionalDeploymentComponent == '' }}
        uses: ./mcbscore/github/actions/deploy-microservice-action
        with:
          component: ${{ github.event.inputs.component }}
          stage: ${{ github.event.inputs.environment }}
          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
          dockerImage: ghcr.io/freenet-group/mcbs-core/ms-${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }}
          checkMkUser: ${{ env.CHECKMK_USER }}
          checkMkSecret: ${{ env.CHECKMK_PW }}
          deploymentUser: ${{ env.DEPLOYMENT_USER }}
          dockerRegistryToken: ${{ env.TOKEN }}

      # Custom Deployment
      - name: Deployment
        id: additionalDeployment
        if: ${{ github.event.inputs.additionalDeploymentComponent != '' }}
        uses: ./mcbscore/github/actions/deploy-microservice-action
        with:
          component: ${{ github.event.inputs.additionalDeploymentComponent }}
          stage: ${{ github.event.inputs.environment }}
          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
          checkMkUser: ${{ env.CHECKMK_USER }}
          checkMkSecret: ${{ env.CHECKMK_PW }}
          deploymentUser: ${{ env.DEPLOYMENT_USER }}

      # Deployment als erfolgreich markieren
      - name: Update deployment status (success)
        if: success()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ env.TOKEN }}
          state: "success"
          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

      # Deployment als fehlerhaft markieren
      - name: Update deployment status (failure)
        if: failure()
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ env.TOKEN }}
          state: "failure"
          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

    outputs:
      componentName: ${{ env.JIRA_COMPONENT }}

  bambi-notification:
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, vm]
    needs: deploy
    if: ${{ always() && !contains(needs.deploy.result, 'failure') && !contains(needs.deploy.result, 'cancelled') && inputs.bambiNotification == 'true' }}
    steps:
      # Deployment als erfolgreich melden
      - name: Report deployment status
        shell: bash
        run: |
          curlResult=$(curl -sw %{http_code} --location --request POST 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v2/bambi/deployment/environmentversion' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "version": "${{ github.event.inputs.componentVersion }}",
            "componentName": "${{ needs.deploy.outputs.componentName }}",
            "workflowName": "${{ github.workflow }}",
            "environment": "${{ github.event.inputs.environment }}",
            "extern": false,
            "workflowRunId": ${{ github.run_id }},
            "deployState": "successfull",
            "deployUser": "${{ github.actor }}"
          }')
          echo "Result: $curlResult"
          statusCode="${curlResult:${#curlResult}-3}"
          echo "statusCode: $statusCode"
          
          if [[ "statusCode" -ge "400" ]]; then
            echo "Result: $curlResult"
            exit 1
          fi