name: DeploymentDockerDB

# Kontrolliert, welche Events die Action auslösen
on:
  push:
    branches:
      - develop

jobs:
  deploy:
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, vm]

    steps:
      # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
      - name: Change Owner to Runner User
        if: ${{ always() }}
        run: |
          docker run --rm -v `pwd`:/target -w /target -t docker-base.mobilcom.de/ubuntu/ubuntu_1804_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

      # Leeren Workspace sicherstellen
      - name: Ensure clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf *

      # ##################################################################################
      # AWS Secrets
      # ##################################################################################

      # Secrets aus AWS auslesen
      - name: Read and set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'eu-central-1'

      - name: Read AWS Parameters
        uses: dkershner6/aws-ssm-getparameters-action@v1
        with:
          parameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/ssh/mcbstest_id_rsa = ID_RSA

      # Repository auschecken unter $GITHUB_WORKSPACE
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ env.TOKEN }}

      # DB-Dateien packen
      - name: create db tar
        run: |
          tar -cvzf importer-database.tar.gz importer-database

      # Docker-DB-Dateien kopieren
      - name: copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DB_SERVER_HOST }}
          username: ${{ secrets.DB_SERVER_USER }}
          key: ${{ env.ID_RSA }}
          #key_path: ./my_id_rsa
          port: ${{ secrets.DB_SERVER_PORT }}
          source: "importer-database.tar.gz"
          target: "db-container-importer"

      # Docker-DB herunterfahren, Dateien entpacken, Docker-DB starten
      - name: multiple command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DB_SERVER_HOST }}
          username: ${{ secrets.DB_SERVER_USER }}
          key: ${{ env.ID_RSA }}
          port: ${{ secrets.DB_SERVER_PORT }}
          script_stop: true
          script: |
            cd db-container-importer
            sh stopLocalDb.sh
            tar -xvzf importer-database.tar.gz
            sh runLocalDbInBg.sh
            rm importer-database.tar.gz
