name: Deployment
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: Deployment ${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }} auf ${{ github.event.inputs.environment }}

on:
  workflow_dispatch:
    inputs:
      component:
        description: Der Name der Komponente
        required: true
      componentVersion:
        description: Die Version der Komponente
        required: true
      additionalDeploymentComponent:
        description: Ermöglicht Deployment unter anderem Namen
        required: false
      environment:
        description: Die Zielumgebung
        required: true
      platforms:
        description: Die Zielserver-Plattform(en)
        type: choice
        options: [ "vm, k8s", "vm", "k8s" ]
        required: false
        default: "vm, k8s"
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        type: string
        required: false
        default: main
      deploymentRepositoryBranch:
        description: Branch von Repository ms-deployment, der benutzt werden soll
        required: false
        default: main
  workflow_call:
    inputs:
      component:
        description: Der Name der Komponente
        required: true
        type: string
      componentVersion:
        description: Die Version der Komponente
        required: true
        type: string
      additionalDeploymentComponent:
        description: Ermöglicht Deployment unter anderem Namen
        required: false
        type: string
      environment:
        description: Die Zielumgebung
        required: true
        type: string
      platforms:
        description: Die Zielserver-Plattform(en); gültige Werte siehe gleichnamiger workflow_dispatch Input
        type: string
        required: false
        default: "vm, k8s"
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        type: string
        required: false
        default: main
      deploymentRepositoryBranch:
        description: Branch von Repository ms-deployment, der benutzt werden soll
        required: false
        default: main
        type: string


env:
  ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
  ACTIONS_PATH: mcbscore/github
  DEPLOYMENT_PATH: mcbscore/deployment
  NODEJS_VERSION: 20

jobs:
  create-deployment:
    runs-on: ubuntu-latest

    steps:
      - name: Show Params
        env:
          INPUTS_JSON: ${{ toJSON(inputs) }}
        run: printf '%s\n' "$INPUTS_JSON"

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read and set AWS credentials
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: Determine deployment ref
        shell: bash
        run: |
          if  [[ ${{ github.event.inputs.componentVersion }} =~ '-SNAPSHOT' ]] ;
          then
            echo "DEPLOYMENT_REF=develop" >> $GITHUB_ENV
          else
            echo "DEPLOYMENT_REF=${{ github.event.inputs.componentVersion }}" >> $GITHUB_ENV
          fi

      - name: Create GitHub deployment
        uses: chrnorm/deployment-action@v2
        id: create-deployment
        with:
          token: ${{ env.TOKEN }}
          environment: ${{ inputs.environment }}
          description: "Deployment auf ${{ inputs.platforms }}"
          ref: ${{ env.DEPLOYMENT_REF }}

    outputs:
      deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}

  deploy:
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, k8s]
    needs: create-deployment
    # if: platforms enthält "vm" ", "-separiert (wie in choice Input) || ","-separiert (evtl in string Input)
    if: contains(format(', {0}, ', inputs.platforms), ', vm, ') || contains(format(',{0},', inputs.platforms), ',vm,')
    steps:
      - name: Change Owner to Runner User
        if: ${{ always() }}
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
          docker run --rm -v `pwd`:/target -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

      - name: Ensure clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf *

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/deployment_user = DEPLOYMENT_USER,
            /github/secrets/ssh/mdmcbsapi-app/zxrestapi_ppk = SSH_KEY,
            /github/secrets/checkmk_user = CHECKMK_USER,
            /github/secrets/checkmk_password = CHECKMK_PW

      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ inputs.actionsRepositoryBranch }}

      - name: Checkout Deployment Data / Scripts
        uses: actions/checkout@v4
        with:
          repository: freenet-group/ms-deployment
          token: ${{ env.TOKEN }}
          path: ${{ env.DEPLOYMENT_PATH }}
          ref: ${{ github.event.inputs.deploymentRepositoryBranch }}

      - name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJavaWithNashornEngine: true
          installNodeJs: true
          installJq: true

      - name: Download Release
        id: downloadRelease
        uses: ./mcbscore/github/actions/download-release-assets
        with:
          version: ${{ github.event.inputs.componentVersion }}
          assetPattern: '-${{ github.event.inputs.componentVersion }}.jar'
          targetPath: './${{ env.DEPLOYMENT_PATH }}/release'
          token: ${{ env.TOKEN }}

      - name: Standard Deployment
        id: deployRelease
        if: ${{ github.event.inputs.additionalDeploymentComponent == '' }}
        uses: ./mcbscore/github/actions/deploy-microservice
        with:
          component: ${{ github.event.inputs.component }}
          stage: ${{ github.event.inputs.environment }}
          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
          dockerImage: ghcr.io/freenet-group/mcbs-core/ms-${{ github.event.inputs.component }}:${{ github.event.inputs.componentVersion }}
          checkMkUser: ${{ env.CHECKMK_USER }}
          checkMkSecret: ${{ env.CHECKMK_PW }}
          deploymentUser: ${{ env.DEPLOYMENT_USER }}
          sshKey: ${{ env.SSH_KEY }}
          dockerRegistryToken: ${{ env.TOKEN }}

      - name: Custom Deployment
        id: additionalDeployment
        if: ${{ github.event.inputs.additionalDeploymentComponent != '' }}
        uses: ./mcbscore/github/actions/deploy-microservice
        with:
          component: ${{ github.event.inputs.additionalDeploymentComponent }}
          stage: ${{ github.event.inputs.environment }}
          componentConfigPath: ${{ env.DEPLOYMENT_PATH }}
          checkMkUser: ${{ env.CHECKMK_USER }}
          checkMkSecret: ${{ env.CHECKMK_PW }}
          deploymentUser: ${{ env.DEPLOYMENT_USER }}
          sshKey: ${{ env.SSH_KEY }}

    outputs:
      componentName: ${{ env.JIRA_COMPONENT }}

  deploy_k8s:
    needs: [create-deployment]
    # if: platforms enthält "k8s" ", "-separiert (wie in choice Input) || ","-separiert (evtl in string Input)
    if: contains(format(', {0}, ', inputs.platforms), ', k8s, ') || contains(format(',{0},', inputs.platforms), ',k8s,')
    uses: freenet-group/mcbscore-reusable-workflows/.github/workflows/deployment_k8s.yml@ae79c6c4c586ae3e1d31665df2cd3ab94d1ebf73
    secrets: inherit
    with:
      componentVersion: ${{ github.event.inputs.componentVersion }}
      environment: ${{ github.event.inputs.environment }}
      component: ${{ github.event.inputs.component }}

  deployment_status:
    needs: [create-deployment, deploy, deploy_k8s]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: Update deployment status (failure)
        if: contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ env.TOKEN }}
          state: "failure"
          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

      - name: Update deployment status (success)
        if: ${{ !(contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled')) }}
        uses: chrnorm/deployment-status@v2
        with:
          token: ${{ env.TOKEN }}
          state: "success"
          deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

  sanity_test:
    needs: [deploy, deploy_k8s]
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, k8s]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read and set AWS credentials
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v4
        with:
          repository: '${{ env.ACTIONS_REPOSITORY }}'
          token: '${{ env.TOKEN }}'
          path: '${{ env.ACTIONS_PATH }}'
          ref: '${{ inputs.actionsRepositoryBranch }}'

      - name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJava: true
          installNodeJs: true
          installJq: true

      - name: Karate Tests ausführen
        if: env.SANITY_TESTS_ENABLED != 'false'
        uses: ./mcbscore/github/actions/sanity-test
        with:
          component: '${{ inputs.component }}'
          environment: '${{ inputs.environment }}'
          awsAccessKeyId: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          awsSecretAccessKey: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          karateVersion: '${{ env.KARATE_VERSION }}'	#aus workflow.properties per init-workflow
          testDir: './sanityTests'
          testFiles: 'SanityTest.feature'

  developer-portal-upload:
    uses: ./.github/workflows/developerPortal.yml
    secrets: inherit
    with:
      component: "${{ inputs.component }}"
      environment: "${{ inputs.environment }}"
      componentVersion: "${{ inputs.componentVersion }}"
      actionsRepositoryBranch: "${{ inputs.actionsRepositoryBranch }}"

  bambi-notification:
    runs-on: [self-hosted, k8s]
    needs: [deploy, deploy_k8s, developer-portal-upload]
    if: ${{ always() && (github.event.inputs.environment == 'git' || github.event.inputs.environment == 'b2b' || github.event.inputs.environment == 'prod') }}
    steps:
      - name: Ermitteln des Gesamtstatus
        run: |
          failedJobs=""
          delimiter=""
          
          # prüfe, ob deploy failed oder cancelled ist
          if [[ "${{ needs.deploy.result }}" == "failure" ]] || [[ "${{ needs.deploy.result }}" == "cancelled" ]]; then
            failedJobs=${failedJobs}${delimiter}deploy
            delimiter=,
          fi

          # prüfe, ob deploy_k8s failed oder cancelled ist
          if [[ "${{ needs.deploy_k8s.result }}" == "failure" ]] || [[ "${{ needs.deploy_k8s.result }}" == "cancelled" ]]; then
            failedJobs=${failedJobs}${delimiter}deploy_k8s
            delimiter=,
          fi

          # prüfe, ob developer-portal-upload failed oder cancelled ist
          if [[ "${{ needs.developer-portal-upload.result }}" == "failure" ]] || [[ "${{ needs.developer-portal-upload.result }}" == "cancelled" ]]; then
            failedJobs=${failedJobs}${delimiter}developer-portal-upload
            delimiter=,
          fi
          
          if [ -z "$failedJobs" ];
          then
            echo "DEPLOY_STATE=successful" >> $GITHUB_ENV
          else
            echo "DEPLOY_STATE=failure:${failedJobs}" >> $GITHUB_ENV
          fi

      - name: Report deployment status
        shell: bash
        run: |
          curlResult=$(curl -sw %{http_code} --location --request POST 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v2/bambi/deployment/environmentversion' \
          --header 'Content-Type: application/json' \
          --data-raw '{
            "version": "${{ github.event.inputs.componentVersion }}",
            "componentName": "${{ needs.deploy.outputs.componentName }}",
            "originComponentName": "${{ github.event.inputs.component }}",
            "workflowName": "${{ github.workflow }}",
            "environment": "${{ github.event.inputs.environment }}",
            "extern": false,
            "workflowRunId": ${{ github.run_id }},
            "deployState": "${{ env.DEPLOY_STATE }}",
            "deployUser": "${{ github.actor }}"
          }')
          statusCode="${curlResult:${#curlResult}-3}"
          echo "statusCode: $statusCode"

          if [[ "statusCode" -ge "400" ]]; then
            echo "Result: $curlResult"
            exit 1
          fi