name: setGitVersion
description: Setzen der "Version for GIT"
inputs:
  jiraURL:
    description: Organisationsinterne URL des angebundenen JIRA-Systems
    required: true
  jiraCredentials:
    description: Organisationsinterne Credentials (user:password) des angebundenen JIRA-Systems
    required: true
  version:
    description: Die zu setzende Version
    required: true
  issue:
    description: Der Issue (i.a. META-xyz) , in dem die Version hinterlegt werden soll
    required: true  
  atlassianDeveloperTools:
    description: die Version der organisationsinternen AtlassianDeveloperTools (separates Repository)
    required: true
  loglevel:
    description: Das LogLevel der innerhalb der Action ablaufenden AtlassianDeveloperTools
    required: false
    default: info

runs:
  using: "composite"
  steps: 
    - id: setGitVersion
      shell: bash
      run: |
        echo setGitVersion ...
        atlassianToolsDir=./mcbscore/github/atlassian-tools

        java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-${{ inputs.loglevel }}.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{inputs.atlassianDeveloperTools}}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          git_version.GitVersionKt \
          "${{inputs.jiraURL}}" \
          "${{inputs.jiraCredentials}}" \
          "${{inputs.version}}" \
          "${{inputs.issue}}"
