name: Auf PROD Umgebung deployen

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GH_MCBS_TOKEN }}

    steps:
      # Starte "Auf PROD Umgebung deployen"
      - name: Invoke deployment workflow for PROD
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "stage": "prod", "aws_key_name": "AWS_KEY_PROD", "aws_secret_name": "AWS_SECRET_PROD", "componentVersion": "${{ github.event.inputs.componentVersion }}" }'
