name: Pull Request geschlossen

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      stage:
        description: 'Welche Stage soll entfernt werden?'
        required: false

jobs:
  remove-deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      # Setup
      - uses: actions/checkout@v4

      - name: workflow.config einlesen
        id: read-properties
        run: |
          tee -a "$GITHUB_OUTPUT" < .github/workflow.config

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-properties.outputs.NODE_VERSION }}
          cache: 'npm'

      - name: Stage setzen
        id: set-stage
        run: |
          if [ -n "${{ github.event.inputs.stage }}" ]; then
            echo "STAGE=${{ github.event.inputs.stage }}" >> $GITHUB_ENV
          else
            PR_NUMBER=$(echo ${{ github.event.pull_request.number }})
            echo "STAGE=pr-${PR_NUMBER}" >> $GITHUB_ENV
          fi

      - name: Dependencies installieren
        run: npm ci

      # Aufräumen
      - name: Serverless Deployment entfernen
        run: |
          npx sls remove --stage ${{ env.STAGE }} --verbose
