name: Pull Request geschlossen

on:
  pull_request:
    types: [closed]
  workflow_dispatch:
    inputs:
      stage:
        description: 'Welche Stage soll entfernt werden?'
        required: false

jobs:
  remove-deployment:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-central-1
    steps:
      # Setup
      - uses: actions/checkout@v4

      - name: workflow.config einlesen
        id: read-properties
        run: |
          { cat .github/workflow.config; echo; } | tee -a -- "$GITHUB_OUTPUT"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ steps.read-properties.outputs.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com/'

      - name: Dependencies installieren
        run: npm ci --force
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_R_PACKAGES }}

      - name: AWS Cli einrichten für SLS Hooks
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Stage setzen
        id: set-stage
        run: |
          if [ -n "${{ inputs.stage }}" ]; then
            echo "STAGE=${{ inputs.stage }}" >> $GITHUB_OUTPUT
          else
            PR_NUMBER=${{ github.event.pull_request.number }}
            echo "STAGE=pr${PR_NUMBER}" >> $GITHUB_OUTPUT
          fi

      - name: Serverless Deployment entfernen, wenn nicht GIT, PET oder PROD
        env: 
          STAGE: ${{ steps.set-stage.outputs.STAGE }}
        run: |
          echo "Überprüfe Stage: $STAGE"
          if echo "$STAGE" | grep -iqE '^(git|pet|prod)$'; then
            echo "Stage darf nicht entfernt werden"
            exit 1
          fi
          
          # Nutze 'npm run remove' wenn vorhanden, ansonsten fallback auf 'npx serverless remove', 
          if [ -f "package.json" ] && grep -q '"remove":' package.json; then
            npm run remove --stage "$STAGE"
          else
            npx serverless remove --stage "$STAGE"
          fi
