name: Check Single-Component
description: 'Information über den Komponenten-Status'
inputs:
  jiraUrl:
    description: Organisationsinterne URL des angebundenen JIRA-Systems
    required: true
  jiraCredentials:
    description: Organisationsinterne Credentials (user:password) des angebundenen JIRA-Systems
    required: true
  issue:
    description: issu
    required: true
  atlassianToolsVersion:
    description: die Version der organisationsinternen AtlassianDeveloperTools (separates Repository)
    required: true
  logLevel:
    description: Das LogLevel der innerhalb der Action ablaufenden AtlassianDeveloperTools
    required: false
    default: info

runs:
  using: "composite"
  steps: 
    - id: fetchComponentInfos
      shell: bash
      run: |
        echo fetch Infos ...
        echo "*${{ inputs.ISSUES }}*"
        atlassianToolsDir=./mcbscore/github/atlassian-tools
        
        java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-${{ inputs.logLevel }}.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{ inputs.atlassianToolsVersion }}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          issue_info.CheckIfSingleComponentKt \
          ${{ inputs.jiraUrl }} \
          "${{ inputs.jiraCredentials }}" \
          "${{ inputs.issue }}" 
          
        cat singleComponent.properties
        
        