name: Gradle Build
description: Composite-Action zur Durchf체hrung eines Gradle-Builds
inputs:
  gradleCommand:
    description: Das Gradle-Kommando
    required: false
    default: clean build
  gradleDirectory:
    description: Das Verzeichnis, in dem der Build erfolgen soll
    required: false
    default: .
  gradleOptions:
    description: Zus채tzliche optionale Gradle-Parameter
    required: false
  sonarqubeUrl:
    description: Die Sonarqube-URL
    required: false
  sonarqubeToken:
    description: Das Sonarqube-Token
    required: false
  artifactoryUserName:
    description: Login f체r das Artifactory
    required: false
  artifactoryPassword:
    description: Passwort f체r das Artifactory
    required: false

runs:
  using: "composite"
  steps:
    - name: Init Gradle Properties
      shell: bash
      run: echo "GRADLE_PROPERTIES=-PBUILD_TYPE=${{ env.BUILD_TYPE }} -PRAW_VERSION=${{ env.RAW_VERSION }} -PARTIFACT_VERSION=${{ env.COMPONENT_VERSION }} -PGITHUB_USER=${{ env.USER }} -PGITHUB_TOKEN=${{ env.TOKEN }}" >> $GITHUB_ENV

    - name: Set Gradle Command
      shell: bash
      run: echo "GRADLE_COMMAND=${{ inputs.gradleCommand }}" >> $GITHUB_ENV

    - name: Add Sonarqube Gradle Task
      if: env.BUILD_TYPE == 'DEVELOP' && env.COVERAGE_APP != ''
      shell: bash
      run: echo "GRADLE_COMMAND=${{ inputs.gradleCommand }} sonarqube -Dsonar.login=${{ inputs.sonarqubeToken }} -Dsonar.host.url=${{ inputs.sonarqubeUrl }}" >> $GITHUB_ENV

    - name: Add Publish Gradle Task
      if: env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'DEVELOP'
      shell: bash
      run: echo "GRADLE_COMMAND=${{env.GRADLE_COMMAND}} publish" >> $GITHUB_ENV

    - name: Add Artifactory Properties
      if: ${{ inputs.artifactoryUserName != '' && inputs.artifactoryPassword != '' }}
      shell: bash
      run: echo "GRADLE_PROPERTIES=${{env.GRADLE_PROPERTIES}} -PartifactoryUsername=${{ inputs.artifactoryUserName }} -PartifactoryPassword=${{ inputs.artifactoryPassword }}" >> $GITHUB_ENV

    - name: Add Liquibase Properties
      if: env.LIQUIBASE_USERNAME != '' && env.LIQUIBASE_PASSWORD != ''
      shell: bash
      run: echo "GRADLE_PROPERTIES=${{env.GRADLE_PROPERTIES}} -PLI_username=${{ env.LIQUIBASE_USERNAME }} -PLI_password=${{ env.LIQUIBASE_PASSWORD }}" >> $GITHUB_ENV

    # Gradle Build
    - name: Build with Gradle
      shell: bash
      run: |
        workingDirectory=$(pwd)
        cd ${{ inputs.gradleDirectory }}
        sh ./gradlew ${{ env.GRADLE_PROPERTIES }} ${{ env.GRADLE_COMMAND }} ${{ inputs.gradleOptions }}
        cd $workingDirectory