name: Gradle Build
description: Composite Action zur Durchführung eines Gradle Builds
inputs:
  gradleCommand:
    description: Das Gradle Kommando
    required: false
    default: clean build
  publishCommand:
    description: Das Gradle publish Kommando
    required: false
    default: publish
  sonarqubeUrl:
    description: Die Sonarqube URL
    required: false
  sonarqubeToken:
    description: Das Sonarqube Token
    required: false

runs:
  using: "composite"
  steps:
    - name: Set Gradle Command
      run: echo "GRADLE_COMMAND=${{ inputs.gradleCommand }} >> $GITHUB_ENV

    - name: Add Sonarqube Gradle Task
      if: ${{ env.BUILD_TYPE == 'DEVELOP' && env.COVERAGE_APP != '' }}
      run: echo "GRADLE_COMMAND=${{ inputs.gradleCommand }} sonarqube -Dsonar.login=${{ inputs.sonarqubeToken }} -Dsonar.host.url=${{ inputs.sonarqubeUrl }}" >> $GITHUB_ENV

    - name: Add Publish Gradle Task
      if: env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'DEVELOP'
      run: echo "GRADLE_COMMAND=${{env.GRADLE_COMMAND}} ${{ inputs.publishCommand }}" >> $GITHUB_ENV

    # Gradle Build
    - name: Build with Gradle
      run: sh ./gradlew -PBUILD_TYPE=${{ env.BUILD_TYPE }} -PRAW_VERSION=${{ env.RAW_VERSION }} -PARTIFACT_VERSION=${{ env.COMPONENT_VERSION }} -PGITHUB_USER=${{ env.USER }} -PGITHUB_TOKEN=${{ env.TOKEN }} -PartifactoryUsername=${{ secrets.MD_ARTIFACTORY_USER }} -PartifactoryPassword=${{ secrets.MD_ARTIFACTORY_PW }} ${{ env.GRADLE_COMMAND }} ${{ github.event.inputs.gradleOptions }}

