name: Gradle Build
description: Composite Action zur Durchführung eines Gradle Builds
env:
  GRADLE_COMMAND: clean build
  PUBLISH_COMMAND: publish

runs:
  using: "composite"
  steps:
    - name: Add Sonarqube Gradle Task
      if: ${{ env.BUILD_TYPE == 'DEVELOP' && env.COVERAGE_APP != '' }}
      run: echo "GRADLE_COMMAND=${{env.GRADLE_COMMAND}} sonarqube -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }} -Dsonar.host.url=${{ secrets.SONARQUBE_HOST_URL }}" >> $GITHUB_ENV

    - name: Add Publish Gradle Task
      if: env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'DEVELOP'
      run: echo "GRADLE_COMMAND=${{env.GRADLE_COMMAND}} ${{env.PUBLISH_COMMAND}}" >> $GITHUB_ENV

    # Gradle Build
    - name: Build with Gradle
      run: sh ./gradlew -PBUILD_TYPE=${{ env.BUILD_TYPE }} -PRAW_VERSION=${{ env.RAW_VERSION }} -PARTIFACT_VERSION=${{ env.COMPONENT_VERSION }} -PGITHUB_USER=${{ env.USER }} -PGITHUB_TOKEN=${{ env.TOKEN }} -PartifactoryUsername=${{ secrets.MD_ARTIFACTORY_USER }} -PartifactoryPassword=${{ secrets.MD_ARTIFACTORY_PW }} ${{ env.GRADLE_COMMAND }} ${{ github.event.inputs.gradleOptions }}

