name: 'Distribute Workflow'
description: 'Action zur Verteilung eines Workflows'

inputs:
  repositoryName:
    description: Der Name des Repositories
    required: true
  repositoryGroup:
    description: Die Gruppe der Repositories
    required: true
  repositoryBranch:
    description: Der Branch des Repositories
    required: true
  workflows:
    description: Kommaseparierte Liste der zu verteilenden Workflows
    required: true
  awsAccessKeyId:
    description: AWS Access Key Id
    required: true
  awsSecretAccessKey:
    description: AWS Secret Access Key
    required: true

runs:
  using: "composite"
  steps:
    - id: read-aws-secrets
      name: Read AWS Secrets
      uses: ./actions/read-aws-secrets
      with:
        awsAccessKeyId: ${{ inputs.awsAccessKeyId }}
        awsSecretAccessKey: ${{ inputs.awsSecretAccessKey }}
        awsParameterPairs: |
          /github/secrets/mcbs_token = TOKEN,
          /github/secrets/mcbs_user = USER

    # Ziel Repository auschecken
    - uses: actions/checkout@v3
      with:
        repository: freenet-group/${{ inputs.repositoryName }}
        token: ${{ env.TOKEN }}
        path: ${{ inputs.repositoryName }}
        ref: ${{ inputs.repositoryBranch }}

    - name: Remove invalid workflows
      shell: bash
      run: |
        set -e

        # Workflows in grep-freundliche zeilenweise List überführen
        workflowList=$(tr , '\n' <<< '${{ inputs.workflows }}' | sed -e 's/^[[:space:]]*//g')

        workingDirectory=$(pwd)
        workflowDirectory=$workingDirectory/${{ inputs.repositoryName }}/.github/workflows
        cd -- '${{ inputs.repositoryName }}'

        if [ -d "$workflowDirectory" ]; then
          for filename in ./.github/workflows/*.yml; do
            # Pfad und Dateiendung entfernen
            basename=$(basename -- "$filename" .yml)

            if ! grep --fixed --line-regexp --quiet -- "$basename" <<< "$workflowList"; then # $basename not contained in $workflowList
              echo "git rm $filename"
              git rm -- "$filename"
            fi
          done
        fi

        cd -- "$workingDirectory"

    - name: Add or replace workflows
      run: |
        set -e

        # Workflows in ein Array überführen
        IFS=',' read -ra workflowList <<< "${{ inputs.workflows }}"

        workingDirectory=$(pwd)
        workflowDirectory=$workingDirectory/${{ inputs.repositoryName }}/.github/workflows
        cd -- '${{ inputs.repositoryName }}'
        mkdir -p -- "$workflowDirectory"

        for workflowName in "${workflowList[@]}"; do
          workflowName=$(sed -e 's/^[[:space:]]*//' <<< "$workflowName")
          sourceRelative=workflows/${{ inputs.repositoryGroup }}/$workflowName.yml
          source=$workingDirectory/$sourceRelative
          target=./.github/workflows/$(basename -- "$workflowName.yml")

          {
            printf '#\n# Generated by repo %s / workflow %s from file %s\n#\n' '${{ github.repository }}' '${{ github.workflow }}' "$sourceRelative"
            cat <"$source"
          } >| "$target"
          git add -v -- "$target"
        done

        # read-aws-secrets composite action muß in jedes repo
        source=$workingDirectory/actions/read-aws-secrets
        target=./.github/actions/
        cp -r "$source" "$target"
        
        git config user.email "it.abr.abba.entw@md.de"
        git config user.name "${{ env.USER }}"

        # git status
        changesDetected=$(git status --porcelain)

        if [ -n "$changesDetected" ]; then
          echo "git commit + push"
          git commit -av -m "Github Workflows aktualisiert"
          # git push origin ${{ inputs.repositoryBranch }}
          git push
        else
          echo "kein git commit"
        fi
      shell: bash
