name: Set Issue List Done
description: Auswertung der Issues eines Repositories seit dem letzten Tag, Bereitstellen von Issue-Infos für eventuelle Release-Notes, Erzeugen einer neuen Version für ein nachfolgendes Releasebuild
inputs:
  jiraUrl:
    description: Organisationsinterne URL des angebundenen JIRA-Systems
    required: true
  jiraCredentials:
    description: Organisationsinterne Credentials (user:password) des angebundenen JIRA-Systems
    required: true
  issueList:
    description: Liste der beteiligten JIRA-Issues
    required: true
  atlassianToolsVersion:
    description: die Version der organisationsinternen AtlassianDeveloperTools (separates Repository)
    required: true
  logLevel:
    description: Das LogLevel der innerhalb der Action ablaufenden AtlassianDeveloperTools
    required: false
    default: info

runs:
  using: "composite"
  steps: 
    - id: setIssueListDone
      shell: bash
      run: |
        echo setIssueListDone ...
        atlassianToolsDir=./mcbscore/github/atlassian-tools

        java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-${{ inputs.logLevel }}.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{inputs.atlassianToolsVersion}}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          jira_board.SetMS_IssueListDoneKt \
          "${{inputs.jiraUrl}}" \
          "${{inputs.jiraCredentials}}" \
          "${{inputs.issueList}}"