name: Select Github Secrets for AWS
description: Wählt aus den Github Secrets für den AWS Zugriff die zur Umgebung passenden aus und setzt ihre Werte in Umgebungsvariablen

inputs:
  environment:
    description: Die Zielumgebung
    required: true
runs:
  using: composite
  steps:
    - env:
        ENVIRONMENT: ${{ inputs.environment }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_ACCESS_KEY_ID_PROD: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY_PROD: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
      shell: bash
      run: |
        if [ "${ENVIRONMENT^^}" = PROD ]; then
          awsAccessKeyId=${AWS_ACCESS_KEY_ID_PROD:-$AWS_ACCESS_KEY_ID}
          awsSecretAccessKey=${AWS_SECRET_ACCESS_KEY_PROD:-$AWS_SECRET_ACCESS_KEY}
        else
          awsAccessKeyId=${AWS_ACCESS_KEY_ID}
          awsSecretAccessKey=${AWS_SECRET_ACCESS_KEY}
        fi
        printf '%s=%s\n' \
            "AWS_ACCESS_KEY_ID"     "$awsAccessKeyId" \
            "AWS_SECRET_ACCESS_KEY" "$awsSecretAccessKey" \
          >> "$GITHUB_ENV"
