name: Initialize Workflow
description: Generische Action, die zur Initialisierung aller Workflows verwendet werden kann

inputs:
  installJava:
    description: JDK installieren?
    type: boolean
    default: false
  installJavaWithNashornEngine:
    description: JDK mit Nashorn Engine installieren
    type: boolean
    default: false
  installNodeJs:
    description: Node.js installieren?
    type: boolean
    default: false
  installJq:
    description: jq installieren?
    type: boolean
    default: false
  installGithubCli:
    description: Github CLI installieren?
    type: boolean
    default: false
  installMaven:
    description: Maven installieren?
    type: boolean
    default: false
  configurationPrefix:
    description: 'Prefix für workflow.properties Dateien. Beispiel: customer-workflow.properties'
    type: string
    required: false
    default:
  lookupBasePath:
    description: Basispfad für den Lookup der Properties Dateien
    type: string
    required: false
    default: .

runs:
  using: "composite"
  steps:
    # Workflow Properties einlesen
    - name: Read workflow.properties
      shell: bash
      run: |
        # Einlesen der workflow.properties, wenn ein Prefix gesetzt ist
        if [ -n '${{ inputs.configurationPrefix }}' ] && [ -f ${{ inputs.lookupBasePath }}/.github/workflow.properties ]; then { cat ${{ inputs.lookupBasePath }}/.github/workflow.properties; echo; } >> $GITHUB_ENV; fi 
        # Einlesen beider Dateien, da build.properties in workflow.properties umbenannt werden sollte. Somit bleibt es abwärtskompatibel
        if [ -f ${{ inputs.lookupBasePath }}/.github/${{ inputs.configurationPrefix }}workflow.properties ]; then { cat ${{ inputs.lookupBasePath }}/.github/${{ inputs.configurationPrefix }}workflow.properties; echo; } >> $GITHUB_ENV; fi
        if [ -f ${{ inputs.lookupBasePath }}/.github/${{ inputs.configurationPrefix }}build.properties ]; then { cat ${{ inputs.lookupBasePath }}/.github/${{ inputs.configurationPrefix }}build.properties; echo; } >> $GITHUB_ENV; fi

    # JAVA installieren
    - name: Set up JDK
      if: ${{ inputs.installJava == 'true' }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: ${{ env.JAVA_VERSION }}

    # JAVA installieren
    - name: Set up JDK with Nashorn engine
      if: ${{ inputs.installJavaWithNashornEngine == 'true' }}
      uses: actions/setup-java@v3
      with:
        distribution: zulu
        java-version: 11

    # Node.js installieren
    - name: Set up Node.js
      if: ${{ inputs.installNodeJs == 'true' }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ env.NODEJS_VERSION }}

    # jq installieren
    - name: Setup jq
      if: ${{ inputs.installJq == 'true' }}
      uses: freenet-actions/setup-jq@v2

    # Github CLI installieren
    - name: Setup Github CLI
      if: ${{ inputs.installGithubCli == 'true' }}
      uses: freenet-actions/setup-github-cli@v2

    # Maven installieren
    - name: Set up Maven
      if: ${{ inputs.installMaven == 'true' }}
      uses: stCarolas/setup-maven@v4.5
      with:
        maven-version: 3.8.6