name: Get Application Token
description: Action, die ein Access-Token f端r Aufrufe gegen das API-Gateway beschafft
inputs:
  clientId:
    description: Client-ID f端r Applikationstoken
    required: true
  clientSecret:
    description: Client-Secret f端r Applikationstoken
    required: true
  tokenUrl:
    description: URL f端r den Token-Aufruf
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      run : |
        chmod +x  ${{ github.action_path }}/getToken.sh

    - id: get_token
      shell: bash
      run : |
        token=$( ${{ github.action_path }}/getToken.sh ${{ inputs.clientId }} ${{ inputs.clientSecret }} ${{ inputs.tokenUrl }})
        echo "accessToken=$token" >> $GITHUB_OUTPUT

outputs:
  accessToken:
    value: ${{ steps.get_token.outputs.accessToken }}
    description: 'Access token retrieved from the API response'
