name: Encoding auf UTF-8 ändern

# Kontrolliert, welche Events die Action auslösen
on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken unter $GITHUB_WORKSPACE
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch }}
          path: 'encoding'

      # Encoding auf UTF-8 ändern
      - name: Change encoding to UTF-8
        run: |
          cd encoding

          git config user.name github-actions
          git config user.email github-actions@github.com

          find . -type f -not '(' -wholename './.git/*' -o -iname '*.properties' -o -iname '*.xml' ')' -print0 \
          	  | xargs -0 -r file | grep -w "text" | awk -F: '{print $1}' | while IFS= read -r f; do

            encoding=$(file -b --mime-encoding -- "$f")
            msg="$f	(encoding: $encoding)"

            if [ "$encoding" = 'us-ascii' -o "$encoding" = 'utf-8' ]; then
              echo "Skipping   $msg"
            else
              echo "Converting $msg"
              tmp=$(mktemp --tmpdir="$(dirname -- "$f")" -- "$(basename -- "$f").XXXXXX")
              iconv -f $encoding -t utf-8 "$f" >| "$tmp"
              chmod --reference="$f" -- "$tmp"
              chown --reference="$f" -- "$tmp"
              mv -- "$tmp" "$f"
            fi

          done

          CHANGES_DETECTED=$(git status --porcelain | tee /dev/stderr)

          if [ -z "$CHANGES_DETECTED" ]; then
            echo "nothing to commit"
          else
            echo "Committing changes"
            git add --verbose --update
            git commit -m "Encoding auf UTF-8 geändert"
            git push
          fi
