name: Vulnerability Erkennung

on:
  schedule:
    # täglich um 05:00 UTC
    - cron: '0 5 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  dependency-submission:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbs_user = USER

      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4
        with:
          additional-arguments: -PGITHUB_USER=${{ env.USER }} -PGITHUB_TOKEN=${{ env.TOKEN }}
          dependency-graph-include-configurations: '.*runtimeClasspath'