name: Deployment (PIRun, HO-Factoring, Masterdata, Shell)

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: Die Version der Komponente
        required: true
      host:
        description: Der Zielhost
        required: true
        type: choice
        options: [ "QA (metis-app-d2)", "GIT (mdapp-t1)", "Prod (mdapp-p1)" ]
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  deploy:
    # self-hosted Runner für die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, vm]
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github

    steps:
      # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
      - name: Change Owner to Runner User
        if: ${{ always() }}
        run: |
          githubUser='${{ github.actor }}'
          githubToken='${{ secrets.GH_R_PACKAGES }}'
          docker login ghcr.io -u "$githubUser" -p "$githubToken"
          docker run --rm -v "$(pwd):/target" -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

      # Leeren Workspace sicherstellen
      - name: Ensure clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf -- *

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbstest_username = SSH_USER,
            /github/secrets/ssh/mcbstest_id_rsa = SSH_KEY

      # Die internen Actions auschecken
      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ github.event.inputs.actionsRepositoryBranch }}

      # ##################################################################################
      # Initialize Workflow
      # ##################################################################################

      - name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJq: true

      # Download Jars
      - name: Download Release (pirun)
        uses: ./mcbscore/github/actions/download-release-assets
        with:
          version: ${{ env.TAG_PREFIX }}${{ github.event.inputs.componentVersion }}
          assetPattern: metis-pirun-${{ github.event.inputs.componentVersion }}.jar
          targetPath: ./release
          token: ${{ env.TOKEN }}

      - name: Download Release (masterdata)
        uses: ./mcbscore/github/actions/download-release-assets
        with:
          version: ${{ env.TAG_PREFIX }}${{ github.event.inputs.componentVersion }}
          assetPattern: metis-masterdata-${{ github.event.inputs.componentVersion }}.jar
          targetPath: ./release
          token: ${{ env.TOKEN }}

      - name: Download Release (hofactoring)
        uses: ./mcbscore/github/actions/download-release-assets
        with:
          version: ${{ env.TAG_PREFIX }}${{ github.event.inputs.componentVersion }}
          assetPattern: metis-hofactoring-${{ github.event.inputs.componentVersion }}.jar
          targetPath: ./release
          token: ${{ env.TOKEN }}

      - name: Download Release (shell)
        uses: ./mcbscore/github/actions/download-release-assets
        with:
          version: ${{ env.TAG_PREFIX }}${{ github.event.inputs.componentVersion }}
          assetPattern: metis-shell-${{ github.event.inputs.componentVersion }}.jar
          targetPath: ./release
          token: ${{ env.TOKEN }}

      # ssh Konfig
      - name: Setup ssh
        shell: bash
        run: |
          printf '' > id_rsa
          chmod 600 id_rsa
          printf %s "$SSH_KEY" >> id_rsa

      # Release kopieren
      - name: Copy release
        shell: bash
        run: |
          version='${{ github.event.inputs.componentVersion }}'
          hostDescription='${{ github.event.inputs.host }}'
          host="${hostDescription##*\(}" # bis zur "(" abschneiden
          host="${host%\)*}" # ab der ")" abschneiden
          case "${hostDescription^^}" in
            (PROD*) dir=/var/PROD;;
            (GIT*)  dir=/var/GIT;;
            (*)     dir=/var/metis-test/METIS_V3.3;;
          esac

          set -x
          scp -i id_rsa -p release/metis-{pirun,masterdata,hofactoring,shell}-${version}.jar "${SSH_USER}@${host}:${dir}"

      # ssh Konfig aufräumen
      - name: Remove ssh key
        if: always()
        shell: bash
        run: rm -v id_rsa
