name: PostBuild

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Die Release Version
        required: true
      issueList:
        description: Die Liste der integrierten JIRA-Issues
        required: true
      epic:
        description: Das EPIC (JIRA) als Releaseklammer (META-170 = "unbestimmt")
        required: false
        default: META-170
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  postBuild:
    # self-hosted Runner für den Systeminternen Zugriff
    runs-on: [self-hosted, vm]
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github
      MAIL_TEMPLATE: B_MS.ftl
      TEAMS_MAIL: 81f16ea1.freenetgroup.onmicrosoft.com@emea.teams.ms

    steps:
      # Owner für alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
      - name: Change Owner to Runner User
        if: ${{ always() }}
        run: |
          githubUser='${{ github.actor }}'
          githubToken='${{ secrets.GH_R_PACKAGES }}'
          docker login ghcr.io -u "$githubUser" -p "$githubToken"
          docker run --rm -v "$(pwd):/target" -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

      # Leeren Workspace sicherstellen
      - name: Ensure clean workspace
        run: |
          echo "Cleaning up previous run"
          rm -rf -- *

      # Repository auschecken unter $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbstest_credentials = MCBSTEST_CREDENTIALS,
            /github/common/jira/api_url = JIRA_API_URL, 
            /github/common/jira/url = JIRA_WEB_URL,
            /github/common/jira/jira_cloud_web_url = JIRA_CLOUD_WEB_URL,
            /github/secrets/mcbstest_jiracloud_credentials = MCBSTEST_JIRACLOUD_CREDENTIALS,
            /github/common/jira/jira_cloud_url = JIRA_CLOUD_URL 

      # Die internen Actions auschecken
      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ inputs.actionsRepositoryBranch }}

      # ##################################################################################
      # Initialize Workflow
      # ##################################################################################
      - id: init-workflow
        name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJava: true

      # ##################################################################################
      # Erzeugen der Version in JIRA
      # ##################################################################################
      - name: jiraConfig
        uses: ./mcbscore/github/actions/jira-configuration-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: METIS
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          componentList: ${{ env.COMPONENT_LIST }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          
      - name: jiraConfig
        uses: ./mcbscore/github/actions/jira-configuration-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: MCBS
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          componentList: ${{ env.COMPONENT_LIST }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          
      - name: jiraConfig
        uses: ./mcbscore/github/actions/jira-configuration-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: ABRMS
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          componentList: ${{ env.COMPONENT_LIST }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}    

      # ##################################################################################
      # Erzeugen einer CSV-Datei mit ergänzenden Issue-Infos
      # ##################################################################################
      - name: fetchIssueInfos
        uses: ./mcbscore/github/actions/fetch-issue-information
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
                
      - name: listIssueInfos
        run: |
          ls -l
          echo "Issue-Infos :"
          cat issue_info.csv
               
      
      # ##################################################################################
      # Eintrag der fixVersion
      # ##################################################################################
      - name: setFixVersions
        uses: ./mcbscore/github/actions/set-fix-version-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          component: ${{ env.COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          issueList: ${{ inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          included_components: ${{ env.INCLUDED_COMPONENTS }} 

      # ##################################################################################
      # set Issues "done"
      # ##################################################################################
      - name: setIssueListDone
        uses: ./mcbscore/github/actions/set-issue-list-done
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      # ##################################################################################
      # Setzen eines Build-Kommentars an den Issues
      # ##################################################################################
      - name: setIssueComment
        uses: ./mcbscore/github/actions/set-issue-comment
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          comment: 'Releasebuild : ${{ env.COMPONENT }}_${{ inputs.releaseVersion }}'
          issueList: ${{ inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      # ##################################################################################
      # Ermitteln der ZusatzInfos zum Release
      # ##################################################################################
      - name: Fetch Additional Information
        id: fetch-additional-information
        uses: ./mcbscore/github/actions/fetch-additional-information
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      # ##################################################################################
      # Erzeugen einer Releasenote im WIKI
      # ##################################################################################
      # GitHub WIKI Repository in das Unterverzeichnis "markdown" auschecken
      - name: Checkout wiki code
        uses: actions/checkout@v4
        with:
          repository: ${{ github.REPOSITORY }}.wiki
          path: markdown

      - name: Create Release Note
        uses: ./mcbscore/github/actions/create-release-note
        with:
          component: ${{ env.COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          jiraWebUrl: ${{ env.JIRA_WEB_URL }}
          hasConfiguration: ${{ steps.fetch-additional-information.outputs.config }}
          hasSql: ${{ steps.fetch-additional-information.outputs.sql }}
          hasDeployment: "NEIN"
          hasDependencies: "NEIN"
          dependentIssues: "keine"
          coverage: ${{ steps.fetch-coverage.outputs.coverage }}
          releaseUrl: '${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/releases/tag/${{ inputs.releaseVersion }}/${{ env.COMPONENT }}-${{ inputs.releaseVersion }}.jar'
          junitResultUrl: '${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/releases'
          cucumberResultUrl: '${{ github.SERVER_URL }}/${{ github.REPOSITORY }}/releases'
          javaVersion: ${{ env.RELEASENOTES_JAVA_RELEASE }}
          epic: ${{ inputs.epic }}

      # ###################################################################################
      # EPIC / IBN auswerten
      # ###################################################################################
      - name: IBN Datum ermitteln
        id: determine-going-live-date
        uses: ./mcbscore/github/actions/determine-going-live-date
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          epic: ${{ inputs.epic }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      # ###################################################################################
      # Mail-Notification
      # ###################################################################################
      - name: Send notification as mail
        uses: ./mcbscore/github/actions/releasebuild-notification
        with:
          component:  ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ inputs.releaseVersion }}
          goingLiveDate: ${{ steps.determine-going-live-date.outputs.goingLiveDate }}
          issueList: issue_info.csv
          hasSql: ${{ steps.fetch-additional-information.outputs.sql }}
          hasConfiguration: ${{ steps.fetch-additional-information.outputs.config }}
          hasDependencies: "NEIN"
          additionalText: "extra"
          epic: ${{ inputs.epic }}
          webhookUri: ${{ env.TEAMS_MAIL }}
          mailTemplate: ${{ env.MAIL_TEMPLATE }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          repositoryName: ${{ github.REPOSITORY }}
