name: Test-Datenbank initialisieren (ReST-Service)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Die Zielumgebung
        required: true
        type: choice
        options:
          - "Kubernetes Dev (https://metis-dev.md-abr-np.k8s.freenet-group.de)"
          - "Dev (http://metis-app-d1.mobilcom.de:8091)"
          - "Test (http://metis-ws-q11.mobilcom.de:8091)"
      loadTestData:
        description: nach dem Zurücksetzen der Datenbank Testdaten einspielen
        type: boolean
        required: false
        default: false

jobs:
  deploy:
    runs-on: [self-hosted,vm]
    steps:
      # Inputs zu handlichen Variablen umwandeln
      - name: Setup variables
        shell: bash
        run: |
          envDescription='${{ github.event.inputs.environment }}'
          if ! [[ "$envDescription" =~ ^.+[[:space:]]+\((.+)\)$ ]]; then
            printf 'Unerwartetes Format in Umgebung "%s"\n' "$envDescription" >&2
            exit 1
          fi
          printf 'GH_INPUT_BASE_URL=%s\n' "${BASH_REMATCH[1]}" \
            | tee -a -- "$GITHUB_ENV"

      # REST Request
      - name: REST request
        shell: bash
        run: |
          # Der .../reset Endpunkt setzt auch erst zurück.
          # Also reicht ein Request mit Endpunkt je nach Input.
          if ${{ github.event.inputs.loadTestData }}; then
            path=initDB/load
            requestBody='testDataSet=testDataSetFULL.xml'
          else
            path=initDB/reset
            requestBody=
          fi
          set -x
          curl -X POST -d "$requestBody" "${GH_INPUT_BASE_URL}/actuator/${path}"
