name: DB Changes
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: DB Changes ${{ github.event.inputs.component }}-${{ github.event.inputs.componentVersion }}

on:
  workflow_dispatch:
    inputs:
      component:
        description: Der Name der Komponente
        required: true
      componentVersion:
        description: Die Version der Komponente
        required: true
      tagPrefix:
        description: Der Präfix des Tags
        required: false

jobs:
  copyChanges:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          path: source
          ref: sql-${{ github.event.inputs.tagPrefix }}${{ github.event.inputs.componentVersion }}

      - name: Read AWS Secrets
        uses: ./source/.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: DB Changes Repository auschecken
        uses: actions/checkout@v3
        with:
          repository: freenet-group/mcbscore_db-changes
          token: ${{ env.TOKEN }}
          path: target

      - name: Read workflow.properties
        shell: bash
        run: |
          cat ./source/.github/${{ github.event.inputs.component }}_workflow.properties >> $GITHUB_ENV

      - name: DB Changes kopieren
        shell: bash
        env:
          GH_INPUT_COMPONENT: ${{ inputs.component }}
          GH_INPUT_COMPONENT_VERSION: ${{ inputs.componentVersion }}
          GH_INPUT_TAG_PREFIX: ${{ inputs.tagPrefix }}
        run: |
          # Pfade in Array laden
          IFS=',' read -r -a array <<< "$DB_CHANGES_PATHS"
          
          # Alle Inhalte der Pfade aus dem Array kopieren
          for path in "${array[@]}"
          do
            cp -Rv source/$DB_CHANGES_BASE_DIRECTORY$path/* target/$GH_INPUT_COMPONENT/$path
          done
          
          cd target
          git config user.name github-actions
          git config user.email github-actions@github.com

          changesDetected=`git status --porcelain`

          if [ -n "$changesDetected" ]
          then
            git add .
            git commit -m "[Releasebuild] db-changes $GH_INPUT_TAG_PREFIX$GH_INPUT_COMPONENT_VERSION"
            git push
          fi

          git tag -f -a sql-$GH_INPUT_TAG_PREFIX$GH_INPUT_COMPONENT_VERSION -m "tagging sql-$GH_INPUT_TAG_PREFIX$GH_INPUT_COMPONENT_VERSION"
          git push --tags -f