name: Build

on:
  push:
    branches-ignore:
      - release
  pull_request:
    branches-ignore:
      - release
      - develop
  workflow_dispatch:
    inputs:
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github

    steps:
      # Repository auschecken unter $GITHUB_WORKSPACE
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbs_user = USER, 
            /github/secrets/mcbstest_credentials = MCBSTEST_CREDENTIALS,
            /github/common/jira/api_url = JIRA_API_URL,
            /github/secrets/mcbstest_jiracloud_credentials = MCBSTEST_JIRACLOUD_CREDENTIALS,
            /github/common/jira/jira_cloud_url = JIRA_CLOUD_URL

      # Die internen Actions auschecken
      - name: checkout mcbscore-github-actions
        uses: actions/checkout@v3
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ github.event.inputs.actionsRepositoryBranch }}

      # ##################################################################################
      # Initialize Workflow
      # ##################################################################################

      - id: init-workflow
        name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJava: true
          installGithubCli: true
          installJq: true

      # ##################################################################################
      # Version ermitteln
      # ##################################################################################

      - id: determine-build-type-and-branch-name
        name: Determine Build Type And Branch Name
        uses: ./mcbscore/github/actions/build-type-and-branch-name

      - id: determine-component-version
        name: Determine Component Version
        uses: ./mcbscore/github/actions/determine-component-version-jc
        with:
          component: ${{ env.COMPONENT }}
          includedComponents: ${{ env.INCLUDED_COMPONENTS }}

      # ##################################################################################
      # Release bauen
      # ##################################################################################

      - name: Inject Version
        shell: bash
        run: |
          chmod +x ./inject_version.sh
          ./inject_version.sh ${{ env.COMPONENT_VERSION }}

      - name: Commit version
        if: env.BUILD_TYPE == 'RELEASE'
        shell: bash
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git commit -am "[tagging] ${{ env.COMPONENT_VERSION }}"
          git push

      - name: Run Build
        shell: bash
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
          chmod +x ./build.sh
          ./build.sh
          #Dateinamen anpassen
          if [ -e ${{ env.COMPONENT }}-km.tar.gz ]; then
            cp ${{ env.COMPONENT }}-km.tar.gz  ${{ env.COMPONENT }}-km-${{ env.COMPONENT_VERSION }}.tar.gz
          fi
          if [ -e ${{ env.COMPONENT }}-md.tar.gz ]; then
            cp ${{ env.COMPONENT }}-md.tar.gz  ${{ env.COMPONENT }}-md-${{ env.COMPONENT_VERSION }}.tar.gz
          fi
          if [ -e ${{ env.COMPONENT }}-fm.tar.gz ]; then
            cp ${{ env.COMPONENT }}-fm.tar.gz  ${{ env.COMPONENT }}-fm-${{ env.COMPONENT_VERSION }}.tar.gz
          fi
          if [ -e ${{ env.COMPONENT }}-km_k8s.tar.gz ]; then
            cp ${{ env.COMPONENT }}-km_k8s.tar.gz  ${{ env.COMPONENT }}-km-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
          fi
          if [ -e ${{ env.COMPONENT }}-md_k8s.tar.gz ]; then
            cp ${{ env.COMPONENT }}-md_k8s.tar.gz  ${{ env.COMPONENT }}-md-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
          fi
          if [ -e ${{ env.COMPONENT }}-fm_k8s.tar.gz ]; then
            cp ${{ env.COMPONENT }}-fm_k8s.tar.gz  ${{ env.COMPONENT }}-fm-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
          fi

      # Existierende Draft Releases löschen
      - name: Delete draft releases
        if: env.BUILD_TYPE == 'DEVELOP'
        uses: hugo19941994/delete-draft-releases@v1.0.1
        env:
          GITHUB_TOKEN: ${{ env.TOKEN }}

      # Release erstellen und Release-Dateien hinzufügen
      - name: Upload Proxies
        id: upload-proxies
        if: env.BUILD_TYPE == 'RELEASE' || env.BUILD_TYPE == 'DEVELOP'
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.TAG_PREFIX }}${{ env.COMPONENT_VERSION }}
          files: |
            ${{ env.COMPONENT }}-md-${{ env.COMPONENT_VERSION }}.tar.gz
            ${{ env.COMPONENT }}-km-${{ env.COMPONENT_VERSION }}.tar.gz
            ${{ env.COMPONENT }}-fm-${{ env.COMPONENT_VERSION }}.tar.gz
            ${{ env.COMPONENT }}-md-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
            ${{ env.COMPONENT }}-km-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
            ${{ env.COMPONENT }}-fm-${{ env.COMPONENT_VERSION }}_k8s.tar.gz
            secretMappings.txt
          token: ${{ env.TOKEN }}
          name: ${{ env.RELEASE_PREFIX }}${{ env.COMPONENT_VERSION }}
          draft: ${{ env.DRAFT }}

      # ##################################################################################
      # Re-Merge
      # ##################################################################################
      - name: Merge development -> staging
        if: env.BUILD_TYPE == 'RELEASE'
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: release
          target_branch: develop
          github_token: ${{ env.TOKEN }}

      # Starte Deployment auf DEV
      - name: Invoke DEV deployment workflow
        if: env.BUILD_TYPE == 'DEVELOP'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: DEV Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ env.COMPONENT_VERSION }}" }'

      # Starte postBuild auf RELEASE
      - name: Invoke postBuild workflow
        if: env.BUILD_TYPE == 'RELEASE'
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: PostBuild
          token: ${{ env.TOKEN }}
          inputs: '{ "releaseVersion": "${{ env.COMPONENT_VERSION }}" , "issueList": "${{ env.ISSUE_LIST }}" }'
