name: Workflow zum Deployment von lua-Scripten auf nginx

on:
  workflow_call:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true
        type: string
      stage:
        description: Die Zielumgebung
        type: string
        required: true
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        type: string
        required: false
        default: main
      deploymentTarget:
        description: Zielserver f端r das Deployment
        type: string
        required: true
      bambiNotification:
        description: Bambi Notification?
        type: string
        required: false
        default: "false"
      assetPattern:
        description: Name des zu depoyenden Scripts ("oidc_authorization_v2.lua" ist default)
        type: string
        required: false
        default: oidc_authorization_v2.lua


jobs:
  create-deployment:
    runs-on: ubuntu-latest

    steps:
    - name: Show Params
      run: echo '${{ toJSON(inputs) }}'
        
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    # Secrets aus AWS auslesen
    - name: Read and set AWS credentials
      uses:  ./.github/actions/read-aws-secrets
      with:
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        awsParameterPairs: |
          /github/secrets/mcbs_token = TOKEN

    - name: Determine deployment ref
      # DEPLOYMENT_REF Umgebungsvariable setzen
      shell: bash
      run: |
        if  [[ ${{ github.event.inputs.componentVersion }} =~ '-SNAPSHOT' ]] ;
        then
          echo "DEPLOYMENT_REF=develop" >> $GITHUB_ENV
        else
          echo "DEPLOYMENT_REF=${{ github.event.inputs.componentVersion }}" >> $GITHUB_ENV
        fi

    - name: Create GitHub deployment
      uses: chrnorm/deployment-action@v2
      id: create-deployment
      with:
        token: ${{ env.TOKEN }}
        environment: ${{ inputs.stage }}
        ref: ${{ env.DEPLOYMENT_REF }}

    outputs:
      deployment_id: ${{ steps.create-deployment.outputs.deployment_id }}

  deploy:
    # self-hosted Runner f端r die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, k8s]
    needs: create-deployment
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github
      NODEJS_VERSION: 20

    steps:
    # Owner f端r alle Dateien des $GITHUB_WORKSPACE auf den Runner User setzen
    - name: Change Owner to Runner User
      if: ${{ always() }}
      run: |
        docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GH_R_PACKAGES }}
        docker run --rm -v `pwd`:/target -w /target -t ghcr.io/freenet-group/container-base-images/ubuntu_2004_lts:latest sh -c "chown $(id -u):$(id -g) -R /target"

    - name: Ensure clean workspace
      # Leeren Workspace sicherstellen
      run: |
        echo "Cleaning up previous run"
        rm -rf *

    - id: checkout-repository
      # Repository auschecken unter $GITHUB_WORKSPACE
      name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: read-aws-secrets
      name: Read AWS Secrets
      uses: ./.github/actions/read-aws-secrets
      with:
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        awsParameterPairs: |
          /github/secrets/mcbs_token = TOKEN,
          /github/secrets/deployment_user = DEPLOYMENT_USER,
          /github/secrets/ssh/apigw/zxrestapi_ppk = SSH_KEY

    - name: checkout mcbscore-github-actions
      # Die internen Actions auschecken
      uses: actions/checkout@v4
      with:
        repository: ${{ env.ACTIONS_REPOSITORY }}
        token: ${{ env.TOKEN }}
        path: ${{ env.ACTIONS_PATH }}
        ref: ${{ inputs.actionsRepositoryBranch }}

    # ##################################################################################
    # Initialize Workflow
    # ##################################################################################

    - id: init-workflow
      name: Initialize Workflow
      uses: ./mcbscore/github/actions/init-workflow
      with:
        installNodeJs: true
        installJq: true

    - name: Download Release
      uses: ./mcbscore/github/actions/download-release-assets
      with:
        version: ${{ inputs.componentVersion }}
        assetPattern: ${{ inputs.assetPattern }}
        targetPath: './release'
        token: ${{ env.TOKEN }}

    - name: Deployment
      id: deploy-lua-scripts
      uses: ./mcbscore/github/actions/deploy-lua-action
      with:
        pathName: 'release'
        host: ${{ inputs.deploymentTarget }}
        deploymentUser: ${{ env.DEPLOYMENT_USER }}
        sshKey: ${{ env.SSH_KEY }}

    # Deployment als erfolgreich markieren
    - name: Update deployment status (success)
      if: success()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ env.TOKEN }}
        state: "success"
        deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

    # Deployment als fehlerhaft markieren
    - name: Update deployment status (failure)
      if: failure()
      uses: chrnorm/deployment-status@v2
      with:
        token: ${{ env.TOKEN }}
        state: "failure"
        deployment-id: ${{ needs.create-deployment.outputs.deployment_id }}

    outputs:
      componentName: ${{ env.COMPONENT }}

  bambi-notification:
    # self-hosted Runner f端r die Steps benutzen, um Zugriff auf MD Systeme zu haben
    runs-on: [self-hosted, k8s]
    needs: deploy
    if: ${{ always() && !contains(needs.deploy.result, 'failure') && !contains(needs.deploy.result, 'cancelled') && inputs.bambiNotification == 'true' }}
    steps:
    # Deployment als erfolgreich melden
    - name: Report deployment status
      shell: bash
      run: |
        curlResult=$(curl -sw %{http_code} --location --request POST 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v2/bambi/deployment/environmentversion' \
        --header 'Content-Type: application/json' \
        --data-raw '{
          "version": "${{ inputs.componentVersion }}",
          "organisation": "${{ inputs.company }}",
          "componentName": "${{ needs.deploy.outputs.componentName }}",
          "workflowName": "${{ github.workflow }}",
          "environment": "${{ inputs.stage }}",
          "workflowRunId": ${{ github.run_id }},
          "deployState": "successfull",
          "deployUser": "${{ github.actor }}"
        }')
        statusCode="${curlResult:${#curlResult}-3}"
        echo "statusCode: $statusCode"

        if [[ "statusCode" -ge "400" ]]; then
          echo "Result: $curlResult"
          exit 1
        fi
