name: GIT Deployment
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: GIT Deployment ${{ github.event.inputs.componentVersion }}

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true
      deployForKubernetes:
        description: soll für Kubernetes-Zugriff deployt werden?
        type: string
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken unter $GITHUB_WORKSPACE
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      # Starte MD Deployment auf GIT
      - name: Invoke deployment workflow GIT MD
        if: hashFiles('**/deployment_git_md.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT MD Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte MD Extern Deployment auf GIT
      - name: Invoke deployment workflow GIT MD Extern
        if: hashFiles('**/deployment_git_md_extern.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT MD Deployment Extern
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte KM Deployment auf GIT
      - name: Invoke deployment workflow GIT KM
        if: hashFiles('**/deployment_git_km.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT KM Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte KM Extern Deployment auf GIT
      - name: Invoke deployment workflow GIT KM Extern
        if: hashFiles('**/deployment_git_km_extern.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT KM Deployment Extern
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}" , "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte FM Deployment auf GIT
      - name: Invoke deployment workflow GIT FM
        if: hashFiles('**/deployment_git_fm.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT FM Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte FM Extern Deployment auf GIT
      - name: Invoke deployment workflow GIT FM Extern
        if: hashFiles('**/deployment_git_fm_extern.yml') != ''
        uses: benc-uk/workflow-dispatch@v1.2.3
        with:
          workflow: GIT FM Deployment Extern
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}" , "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'
