name: B2B Deployment Lua
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: B2B Deployment Lua

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main
      assetPattern:
        description: Name des zu deployenden Scripts
        type: string
        required: false
        default: oidc_authorization_v2.lua        

jobs:
  deployment:
    uses: ./.github/workflows/deployment_lua.yml
    secrets: inherit
    with:
      componentVersion: ${{ inputs.componentVersion }}
      stage: b2b
      deploymentTarget: apigw-t11.mobilcom.de
      actionsRepositoryBranch: ${{ inputs.actionsRepositoryBranch }}
      assetPattern: ${{ inputs.assetPattern }}
