name: B2B Deployment Lua
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: B2B Deployment Lua

on:
  workflow_dispatch:
    inputs:
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  deployment:
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      stage: b2b
      deploymentTarget: apigw-t11.mobilcom.de
      actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
