name: GIT Deployment Lua
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: GIT Deployment Lua

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true     
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main
      assetPattern:
        description: Name des zu depoyenden Scripts ("oidc_authorization_v2.lua" ist default)
        type: string
        required: false
        default: oidc_authorization_v2.lua

jobs:
  deployment:
    strategy:
        matrix:
          target: [apigw-g1.mobilcom.de, apigw-g2.mobilcom.de]
    uses: ./.github/workflows/deployment_lua.yml
    secrets: inherit
    with:
      componentVersion: ${{ github.event.inputs.componentVersion }}
      stage: git
      deploymentTarget:  ${{ matrix.target }}
      bambiNotification: true
      actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
      assetPattern: ${{ github.event.inputs.assetPattern }}
