name: PROD Deployment Lua
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: PROD Deployment Lua

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  deployment:
    strategy:
        matrix:
          target: [apigw-p1.mobilcom.de, apigw-p2.mobilcom.de, apigw-p3.mobilcom.de]  
    uses: ./.github/workflows/deployment_lua.yml
    secrets: inherit
    with:
      componentVersion: ${{ github.event.inputs.componentVersion }}
      stage: prod
      deploymentTarget: ${{ matrix.target }}
      bambiNotification: true
      actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
