name: B2B Deployment
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: B2B Deployment ${{ github.event.inputs.componentVersion }}

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: true
      deployForKubernetes:
        description: soll für Kubernetes-Zugriff deployt werden?
        type: string
        required: false
        default: "false"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Repository auschecken unter $GITHUB_WORKSPACE
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      # Starte MD Deployment auf B2B
      - name: Invoke deployment workflow B2B MD
        if: hashFiles('**/deployment_b2b_md.yml') != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: B2B MD Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte KM Deployment auf B2B
      - name: Invoke deployment workflow B2B KM
        if: hashFiles('**/deployment_b2b_km.yml') != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: B2B KM Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'

      # Starte FM Deployment auf B2B
      - name: Invoke deployment workflow B2B FM
        if: hashFiles('**/deployment_b2b_fm.yml') != ''
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: B2B FM Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "componentVersion": "${{ github.event.inputs.componentVersion }}", "deployForKubernetes": "${{ github.event.inputs.deployForKubernetes }}" }'