name: GIT Deployment Lua
#Name für den workflow. Wichtig bei mehreren workflows im selben Repository um die workflows im actions-tab unterscheiden zu können.
run-name: GIT Deployment Lua

on:
  workflow_dispatch:
    inputs:
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main

jobs:
  deployment:
    strategy:
        matrix:
          target: [apigw-g1.mobilcom.de, apigw-g2.mobilcom.de]
    uses: ./.github/workflows/deployment.yml
    secrets: inherit
    with:
      stage: git
      deploymentTargets:  ${{ matrix.target }}
      bambiNotification: true
      actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
