name: Check Pull-Request

# Concurrency beendet alle anderen Jobs mit der gleichen Gruppe, wenn ein neuer Job startet
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:

jobs:
  # Syncronisiert die GitHub PR Labels mit den Jira Components
  syncLabels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: AWS Secrets auslesen
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbstest_jiracloud_credentials = MCBSTEST_JIRACLOUD_CREDENTIALS,
            /github/common/jira/jira_cloud_url = JIRA_CLOUD_URL

      - name: Sync GitHub PR Labels with Jira Components
        uses: freenet-group/github-pr-label-sync-with-jira@0.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-labels: ms-deployment:yes, ms-configuration:yes
          jira-components: ms-deployment, ms-configuration
          jira-api-url: ${{ env.JIRA_CLOUD_URL }}
          jira-auth-token: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}

  # Prüft die GitHub PR Labels auf Vollständigkeit
  checkLabels:
    needs: syncLabels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    strategy:
      # Matrix, sodass die einzelnen Label-Checks parallel ausgeführt werden können
      matrix:
        label:
          - name: "Release"
            labels: "release:patch, release:minor, release:major"
            count: 1
            mode: "exactly"
            add_comment: true
            message: "Pull-Request wurde aufgrund fehlender Release-Labels abgelehnt. \n
                      Es muss exakt eines dieser Labels gesetzt werden: \n
                      - release:patch\n
                      - release:minor\n
                      - release:major"
          - name: "MS-Configuration"
            labels: "ms-configuration:yes, ms-configuration:no"
            count: 1
            mode: "exactly"
            add_comment: true
            message: "Pull-Request wurde aufgrund fehlender MS-Configuration-Labels abgelehnt. \n
                      Es muss exakt eines dieser Labels gesetzt werden: \n
                      - ms-configuration:yes\n
                      - ms-configuration:no"
          - name: "MS-Deployment"
            labels: "ms-deployment:yes, ms-deployment:no"
            count: 1
            mode: "exactly"
            add_comment: true
            message: "Pull-Request wurde aufgrund fehlender MS-Deployment-Labels abgelehnt. \n
                      Es muss exakt eines dieser Labels gesetzt werden: \n
                      - ms-deployment:yes\n
                      - ms-deployment:no"

    steps:
      - name: Check ${{ matrix.label.name }} Labels
        if: always()
        uses: mheap/github-action-required-labels@v5
        with:
          count: ${{ matrix.label.count }}
          mode: ${{ matrix.label.mode }}
          add_comment: ${{ matrix.label.add_comment }}
          labels: ${{ matrix.label.labels }}
          message: ${{ matrix.label.message }}

  # Sendet eine Benachrichtigung an die angegebenen Benutzer, wenn bestimmte Labels gesetzt sind
  notifyOnLabel:
    needs: checkLabels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: DOGS Benachrichtigung
        uses: freenet-group/notify-on-label@1.0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label_list: 'ms-configuration:yes, ms-deployment:yes'
          user_name_list: '@freenet-group/abr-ms-gh-deployments'
          pull_request_number: ${{ github.event.pull_request.number }}
