name: Check Code

on:
  pull_request:
    types: [opened, reopened, synchronize]

# Concurrency beendet alle anderen Jobs mit der gleichen Gruppe, wenn ein neuer Job startet
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # Prüft, ob die Dateien UTF-8 kodiert sind
  utf8:
    runs-on: ubuntu-latest
    steps:
      - name: Repository auschecken
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: UTF-8 encoding prüfen und invalide Dateien auflisten
        shell: bash
        run: |
          NON_UTF8_FILES=$(find "$GITHUB_WORKSPACE" -type f -not '(' -iname '*.properties' -o -iname '*.xml' ')' -exec file --mime '{}' ';' \
              | grep --invert-match --perl-regexp '\bcharset=(binary|us-ascii|utf-8)$')
          if [ -n "$NON_UTF8_FILES" ]; then
            echo "Non-UTF-8 encoded files found:"
            echo "$NON_UTF8_FILES"
            exit 1
          fi


  # Prüft, ob gewisse Tags im Code vorhanden sind
  markierungen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Prüf-Kommentar erstellen
        uses: gkampitakis/github-action-todo-commenter@v1
        with:
          comment-title: "Markierungen im Code"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          ignore-pattern: '.yml$|.md$|^\.github/'
          review-message: "Bitte die Einträge prüfen :eyes:"
          tags: "TODO,FIXME,BUG,DOCME,DEPRECATED"
