name: CICD Check Pull-Request

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled, review_requested, review_request_removed]

jobs:
  syncLabels:
    runs-on: ubuntu-latest
    env:
      # expected aws properties
      USER: ''
      TOKEN: ''
      JASYPT_ENCRYPTOR_PASSWORD: ''
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: AWS Secrets auslesen
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbstest_jiracloud_credentials = MCBSTEST_JIRACLOUD_CREDENTIALS,
            /github/common/jira/jira_cloud_url = JIRA_CLOUD_URL

      - name: Sync GitHub PR Labels with Jira Components
        uses: freenet-group/github-pr-label-sync-with-jira@0.1.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-labels: ms-deployment:yes, ms-configuration:yes
          jira-components: ms-deployment, ms-configuration
          jira-api-url: ${{ env.JIRA_CLOUD_URL }}
          jira-auth-token: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}

  labels:
    needs: syncLabels
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Release Labels prüfen
        if: always()
        id: release-labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "release:patch, release:minor, release:major"
          add_comment: true
          message: "Pull-Request wurde aufgrund fehlender Release-Labels abgelehnt. \n
          Es muss exakt eines dieser Labels gesetzt werden: \n
          - release:patch\n
          - release:minor\n
          - release:major"

      - name: MS-Configuration Labels prüfen
        if: always()
        id: ms-configuration-labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "ms-configuration:yes, ms-configuration:no"
          add_comment: true
          message: "Pull-Request wurde aufgrund fehlender MS-Configuration-Labels abgelehnt. \n
          Es muss exakt eines dieser Labels gesetzt werden: \n
          - ms-configuration:yes\n
          - ms-configuration:no"

      - name: MS-Deployment Labels prüfen
        if: always()
        id: ms-deployment-labels
        uses: mheap/github-action-required-labels@v5
        with:
          mode: exactly
          count: 1
          labels: "ms-deployment:yes, ms-deployment:no"
          add_comment: true
          message: "Pull-Request wurde aufgrund fehlender MS-Deployment-Labels abgelehnt. \n
          Es muss exakt eines dieser Labels gesetzt werden: \n
          - ms-deployment:yes\n
          - ms-deployment:no"
