name: CICD PostBuild

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: Die Release-Version
        required: true
      issueList:
        description: Die Liste der integrierten JIRA-Issues
        required: false
      epic:
        description: Das EPIC (JIRA) als Releaseklammer (META-170 = "unbestimmt")
        required: false
        default: META-170
      actionsRepositoryBranch:
        description: Zu benutzender Branch des Repositories mcbscore-github-actions
        required: false
        default: main
      bambiArgs:
        description: 'JSON string for Bambi API call. Should contain fields: ibnDate, changesInConfiguration, changesInDeployment, dbChanges, dependencies, renovateInfo, and renovate.'
        required: false
        default: '{"ibnDate": "", "changesInConfiguration": "", "changesInDeployment": "", "dbChanges": "", "dependencies": "", "renovateInfo": "", "renovate": ""}'

jobs:
  postBuild:
    # self-hosted Runner für den Systeminternen Zugriff
    runs-on: [ self-hosted, k8s ]
    env:
      ACTIONS_REPOSITORY: freenet-group/mcbscore-github-actions
      ACTIONS_PATH: mcbscore/github
      MAIL_TEMPLATE: B_MS.ftl
      TEAMS_MAIL: b48281f2.freenetgroup.onmicrosoft.com@emea.teams.ms
      BAMBI_API_URL: 'https://bambi-api-prod.md-abr-prod.k8s.freenet-group.de/v1/bambi/initialBuild'
      # expected aws properties
      TOKEN: ''
      MCBSTEST_CREDENTIALS: ''
      JIRA_API_URL: ''
      JIRA_CLOUD_WEB_URL: ''
      SONAR_API_URL: ''
      JIRA_URL2: ''
      MCBSTEST_JIRACLOUD_CREDENTIALS: ''
      JIRA_CLOUD_URL: ''

    outputs:
      coverage: ${{ steps.fetch-coverage.outputs.coverage }}
      sql: ${{ steps.fetch-additional-information.outputs.sql }}
      config: ${{ steps.fetch-additional-information.outputs.config }}
      dependency: ${{ steps.fetch-additional-information.outputs.dependency }}
      going_live_date: ${{ steps.determine-going-live-date.outputs.goingLiveDate }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: AWS Secrets auslesen
        id: read-aws-secrets
        uses: ./.github/actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN,
            /github/secrets/mcbstest_credentials = MCBSTEST_CREDENTIALS,
            /github/common/jira/api_url = JIRA_API_URL, 
            /github/common/jira/jira_cloud_web_url = JIRA_CLOUD_WEB_URL,
            /github/common/sonar/api_url = SONAR_API_URL,
            /github/common/JIRA_URL2 = JIRA_URL2,
            /github/secrets/mcbstest_jiracloud_credentials = MCBSTEST_JIRACLOUD_CREDENTIALS,
            /github/common/jira/jira_cloud_url = JIRA_CLOUD_URL

      - name: Checkout mcbscore-github-actions
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ACTIONS_REPOSITORY }}
          token: ${{ env.TOKEN }}
          path: ${{ env.ACTIONS_PATH }}
          ref: ${{ github.event.inputs.actionsRepositoryBranch }}

      - name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJava: true

      - name: Konfiguriere Jira für ABRMS Projekt
        uses: ./mcbscore/github/actions/jira-configuration-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: ABRMS
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ github.event.inputs.releaseVersion }}
          componentList: '${{ env.JIRA_COMPONENT }},ABRMS (unspez.)'
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Konfiguriere Jira für MCBS Projekt
        uses: ./mcbscore/github/actions/jira-configuration-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: MCBS
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ github.event.inputs.releaseVersion }}
          componentList: '${{ env.JIRA_COMPONENT }},Microservices'
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Weitere Infos zur IssueList holen
        uses: ./mcbscore/github/actions/fetch-issue-information
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ github.event.inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Release bei Bambi melden
        run: |
          issueListWithDelimiter=$(echo "${{ github.event.inputs.issueList }}" | tr -s ' ' ',')
          echo "Create BAMBI-Entry for IssueList: $issueListWithDelimiter"

          bambiArgs='${{ github.event.inputs.bambiArgs }}'
          echo "bambiArgs: $bambiArgs"
          
          changesInConfiguration=$(echo "$bambiArgs" | jq -r '.changesInConfiguration')
          changesInDeployment=$(echo "$bambiArgs" | jq -r '.changesInDeployment')
          dbChanges=$(echo "$bambiArgs" | jq -r '.dbChanges')
          dependencies=$(echo "$bambiArgs" | jq -r '.dependencies')
          ibnDate=$(echo "$bambiArgs" | jq -r '.ibnDate')
          renovateInfo=$(echo "$bambiArgs" | jq -r '.renovateInfo')
          renovate=$(echo "$bambiArgs" | jq -r '.renovate')

          requestBody="{
            \"buildInfo\": {
              \"ibnDate\": \"$ibnDate\",
              \"changesInConfiguration\": \"$changesInConfiguration\",
              \"changesInDeployment\": \"$changesInDeployment\",
              \"dbChanges\": \"$dbChanges\",
              \"dependencies\": \"$dependencies\",
              \"renovateInfo\": \"$renovateInfo\"
            },
            \"buildUser\": \"mcbstest\",
            \"componentName\": \"${{ env.JIRA_COMPONENT }}\",
            \"issueList\": \"$issueListWithDelimiter\",
            \"renovate\": \"$renovate\",
            \"versionNo\": \"${{ github.event.inputs.releaseVersion }}\"
          }"
          echo "Bambi RequestBody: $requestBody"

          http_response=$(curl -w "%{http_code}\n" --location --request POST "${{ env.BAMBI_API_URL }}" --header "Content-Type: application/json" --data-raw "$requestBody")
          echo "Response: ${http_response}"

          http_code=$(echo "$http_response" | cut -d '}' -f 2)
          if [ "$http_code" != "200" ]; then
            exit 1
          fi

      - name: FixVersion bei Jira eintragen
        uses: ./mcbscore/github/actions/set-fix-version-jc
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ github.event.inputs.releaseVersion }}
          issueList: ${{ github.event.inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          included_components: ${{ env.INCLUDED_COMPONENTS }}

      - name: Release Version als Kommentar im Ticket eintragen
        uses: ./mcbscore/github/actions/set-issue-comment
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          comment: 'Releasebuild : ${{ env.JIRA_COMPONENT }}_${{ github.event.inputs.releaseVersion }}'
          issueList: ${{ github.event.inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Jira Status auf geschlossen setzen
        uses: ./mcbscore/github/actions/set-issue-list-closed
        with:
          jiraURL: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ github.event.inputs.issueList }}
          atlassianDeveloperTools: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          loglevel: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_LOGLEVEL }}

      # @todo Prüfen ob dies nicht mehr in den Pre-Merge Checks Sinn macht
      - name: Sonar-Coverage einholen
        id: fetch-coverage
        if: ${{ (env.JAVA_VERSION != '8') && (env.COVERAGE_APP != '') }}
        uses: ./mcbscore/github/actions/sonar-check
        with:
          sonarUrl: ${{ env.SONAR_API_URL }}
          sonarCredentials: ${{ env.MCBSTEST_CREDENTIALS }}
          projectKeyPath: ${{ env.COVERAGE_PATH }}
          projectKeyName: ${{ env.COVERAGE_APP }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Sonar-Coverage prüfen
        if: ${{ (env.JAVA_VERSION != '8') && (env.COVERAGE_APP != '') && (steps.fetch-coverage.outputs.coverage < env.COVERAGE_LIMIT) && (env.COVERAGE_FAIL == 'TRUE') }}
        uses: ./mcbscore/github/actions/create-sonar-issue
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          jiraProject: ${{ env.JIRA_PROJECT }}
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ github.event.inputs.releaseVersion }}
          coverageLimit: ${{ env.COVERAGE_LIMIT }}
          coverage: ${{ steps.fetch-coverage.outputs.coverage }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Zusatzinformationen zum Release holen
        id: fetch-additional-information
        uses: ./mcbscore/github/actions/fetch-additional-information
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          issueList: ${{ github.event.inputs.issueList }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: IBN Datum ermitteln
        id: determine-going-live-date
        uses: ./mcbscore/github/actions/determine-going-live-date
        with:
          jiraUrl: ${{ env.JIRA_CLOUD_URL }}
          jiraCredentials: ${{ env.MCBSTEST_JIRACLOUD_CREDENTIALS }}
          epic: ${{ github.event.inputs.epic }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}

      - name: Info an Teams Kanal senden
        if: ${{ github.event.inputs.renovate == 'false' }}
        uses: ./mcbscore/github/actions/releasebuild-notification
        with:
          component: ${{ env.JIRA_COMPONENT }}
          componentVersion: ${{ github.event.inputs.releaseVersion }}
          goingLiveDate: ${{ steps.determine-going-live-date.outputs.goingLiveDate }}
          issueList: issue_info.csv
          hasSql: ${{ steps.fetch-additional-information.outputs.sql }}
          hasConfiguration: ${{ steps.fetch-additional-information.outputs.config }}
          hasDependencies: ${{ steps.fetch-additional-information.outputs.dependency }}
          additionalText: "extra"
          epic: ${{ github.event.inputs.epic }}
          webhookUri: ${{ env.TEAMS_MAIL }}
          mailTemplate: ${{ env.MAIL_TEMPLATE }}
          atlassianToolsVersion: ${{ env.ATLASSIAN_DEVELOPER_TOOLS_VERSION }}
          repositoryName: ${{ github.REPOSITORY }}

