name: Read AWS Secrets
description: Liest Parameter aus dem AWS Parameter Store ein

inputs:
  awsAccessKeyId:
    description: AWS Access Key Id
  awsSecretAccessKey:
    description: AWS Secret Access Key
  awsParameterPairs:
    description: auszulesende AWS Parameter
    default: |
      /github/secrets/mcbs_token = TOKEN

runs:
  using: "composite"
  steps:
    # Secrets aus AWS auslesen
    - name: Read and set AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.awsAccessKeyId }}
        aws-secret-access-key: ${{ inputs.awsSecretAccessKey }}
        aws-region: 'eu-central-1'

    - name: Read AWS Parameters
      uses: dkershner6/aws-ssm-getparameters-action@v1
      with:
        parameterPairs: ${{ inputs.awsParameterPairs }}