name: Auf Spielwiese deployen

on:
  workflow_dispatch:
    inputs:
      componentVersion:
        description: 'Die Version der Komponente'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.GH_MCBS_TOKEN }}

    steps:
      # Starte "Auf Spielwiese deployen"
      - name: Invoke deployment workflow for playground
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deployment
          token: ${{ env.TOKEN }}
          inputs: '{ "stage": "dev", "aws_key_name": "AWS_KEY_PLAYGROUND", "aws_secret_name": "AWS_SECRET_PLAYGROUND", "componentVersion": "${{ github.event.inputs.componentVersion }}" }'