name: Von Umgebung entfernen

on:
  workflow_dispatch:
    inputs:
      stage:
        description: 'Die Ziel Stage'
        required: true
      aws_key_name:
        description: 'Der Name des AWS Key Secrets'
        required: true
      aws_secret_name:
        description: 'Der Name des AWS Secret Secrets'
        required: true

jobs:
  remove:
    runs-on: ubuntu-latest
    steps:
      # Repository auschecken unter $GITHUB_WORKSPACE
      - id: checkout-repository
        name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      # ##################################################################################
      # Initialize Workflow
      # ##################################################################################

      - id: init-workflow
        name: Initialize Workflow
        uses: ./mcbscore/github/actions/init-workflow
        with:
          installJava: true
          installGithubCli: true
          installJq: true

      - name: Install Serverless Framework
        run: npm install -g serverless

      - name: Serverless AWS authentication
        run: sls config credentials --provider aws --key ${{ secrets[inputs.aws_key_name] }} --secret ${{ secrets[inputs.aws_secret_name] }}

      - name: Install NPM dependencies
        run: npm install

      - name: Remove Lambda functions
        run: sls remove --stage ${{ inputs.stage }}
