name: Fetch Additional Information
description: 'Auswertung der Issues eines Release bzgl. dependencies , sql , config und Bereitstellung nach aussen'
inputs:
  jiraUrl:
    description: Organisationsinterne URL des angebundenen JIRA-Systems
    required: true
  jiraCredentials:
    description: Organisationsinterne Credentials (user:password) des angebundenen JIRA-Systems
    required: true
  issueList:
    description: Liste der beteiligten Issues
    required: true
  atlassianToolsVersion:
    description: die Version der organisationsinternen AtlassianDeveloperTools (separates Repository)
    required: true
  logLevel:
    description: Das LogLevel der innerhalb der Action ablaufenden AtlassianDeveloperTools
    required: false
    default: info
  
outputs:
  config:
    description: Indikator für ms-configuration
    value: ${{ steps.fetchAdditionalInfo.outputs.config }}
  dependency:
    description: Indikator für dependency-Einträge
    value: ${{ steps.fetchAdditionalInfo.outputs.dependency }}  
  dependentIssues:
    description: konkrete Abhängigkeiten
    value: ${{ steps.fetchAdditionalInfo.outputs.dependentIssues }}
  sql:
    description: Indikator für db-changes
    value: ${{ steps.fetchAdditionalInfo.outputs.sql }}  

env:
  CONFIG: "true"
  SQL: "true"
  DEPENDENCY: "true"
  DEPENDENT_ISSUES: "none"

runs:
  using: "composite"
  steps: 
    - id: fetchAdditionalInfo
      shell: bash
      run: |
        echo fetchAdditionalInfo ...
        atlassianToolsDir=./mcbscore/github/atlassian-tools
        
        # Dependencies auswerten      
        # java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-${{ inputs.logLevel }}.xml \
        #   -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{ inputs.atlassianToolsVersion }}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
        #   dev_config.GetDependencyKt \
        #   ${{ inputs.jiraUrl }} \
        #   ${{ inputs.jiraCredentials }} \
        #   "${{ inputs.issueList }}"
        
        # Liste / Property-File der Abhängigkeiten auslesen
        # while IFS='=' read -r key value
        # do
        #   eval ${key}=${value}
        # done < dependendIssues.properties
        # echo "Dependency       = " ${dependendIssueList}
        # echo "DEPENDENT_ISSUES=$(echo $dependendIssueList)" >> $GITHUB_ENV
        echo "DEPENDENT_ISSUES=keine" >> $GITHUB_ENV

        # Liste als Variable bereitstellen
        # echo "dependentIssues=$dependendIssueList" >> $GITHUB_OUTPUT
        echo "dependentIssues=keine" >> $GITHUB_OUTPUT
        
        # Dependencies TRUE || FALSE
        # while IFS='=' read -r key value
        # do
        #   eval ${key}=${value}
        # done < dependency.properties
        # if [ "$dependency" = "true" ]; then dependency="JA"; else dependency="NEIN"; fi 
        # echo "Dependency       = " ${dependency}
        # echo "DEPENDENCY=$(echo $dependency)" >> $GITHUB_ENV
        echo "DEPENDENCY=NEIN" >> $GITHUB_ENV

        # Variable bereitstellen
        # echo "dependency=$dependency" >> $GITHUB_OUTPUT
        echo "dependency=NEIN" >> $GITHUB_OUTPUT
        
        # DB-Changes auswerten
        java -Dlog4j2.configurationFile="$atlassianToolsDir"/log4j2-${{ inputs.logLevel }}.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{ inputs.atlassianToolsVersion }}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          dev_config.GetSQLUpdateKt \
          ${{ inputs.jiraUrl }} \
          ${{ inputs.jiraCredentials }} \
          "${{ inputs.issueList }}" 

        while IFS='=' read -r key value
        do
          eval ${key}=${value}
        done < sql.properties
        if [ "$sql" = "true" ]; then sql="JA"; else sql="NEIN"; fi 
        echo "SQL       = " ${sql}
        echo "SQL=$(echo $sql)" >> $GITHUB_ENV

        # Variable bereitstellen
        echo "sql=$sql" >> $GITHUB_OUTPUT
        
        # Config auswerten
        java -Dlog4j2.configurationFile="$atlassianToolsDir"s/log4j2-${{ inputs.logLevel }}.xml \
          -cp "$atlassianToolsDir"/AtlassianDeveloperTools-all-${{ inputs.atlassianToolsVersion }}.jar:.:"$atlassianToolsDir"/AtlassianDeveloperTools \
          dev_config.GetConfigKt \
          ${{ inputs.jiraUrl }} \
          ${{ inputs.jiraCredentials }} \
          "${{ inputs.issueList }}"  

        while IFS='=' read -r key value
        do
          eval ${key}=${value}
        done < config.properties
        if [ "$config" = "true" ]; then config="JA"; else config="NEIN"; fi 
        echo "Configuration       = " ${config}
        echo "CONFIG=$(echo $config)" >> $GITHUB_ENV

        # Version als Variable bereitstellen
        echo "config=$config" >> $GITHUB_OUTPUT
