name: Distribute

on:
  workflow_dispatch:
    inputs:
      group:
        description: 'Zu aktualisierende Gruppe'
        type: choice
        required: true
        default: ALL
        options:
          - ALL
          - mslib
          - test

jobs:
  mslib:
    if: ${{ github.event.inputs.group == 'mslib' || github.event.inputs.group == 'ALL' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - { name: mcbscore-github-test-repo, branch: main, group: standard, workflows: "../check, build, ../encoding, postBuild" }
#          - { name: mslib-aws, branch: develop, group: standard, workflows: "../check, build, ../encoding, postBuild" }
#          - { name: mslib-rest, branch: develop, group: standard, workflows: "../check, build, ../encoding, postBuild" }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Distribute Workflows
        id: distributeWorkflows
        uses: ./.github/actions/distribute-workflows-action
        with:
          repositoryName: ${{ matrix.repository.name }}
          repositoryBranch: ${{ matrix.repository.branch }}
          actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

  test:
    if: ${{ github.event.inputs.group == 'test' || github.event.inputs.group == 'ALL' }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repository:
          - { name: mcbscore-github-test-repo, branch: main, group: standard, workflows: "../check, build, ../encoding, postBuild" }
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Distribute Workflows
        id: distributeWorkflows
        uses: ./.github/actions/distribute-workflows-action
        with:
          repositoryName: ${{ matrix.repository.name }}
          repositoryBranch: ${{ matrix.repository.branch }}
          actionsRepositoryBranch: ${{ github.event.inputs.actionsRepositoryBranch }}
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
