name: List MCBS Core Repos

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ inputs.awsAccessKeyId }}
          awsSecretAccessKey: ${{ inputs.awsSecretAccessKey }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: Initialize Workflow
        uses: ./actions/init-workflow
        with:
          installGithubCli: true

      - name: List Repos
        shell: bash
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/freenet-group/teams/mcbs-core/repos
        env:
          GH_TOKEN: ${{ env.TOKEN }}