name: List MCBS Core Repos

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Github CLI installieren
        uses: freenet-actions/setup-github-cli@v2

      - name: List Repos
        shell: bash
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            /orgs/freenet-group/teams/mcbs-core/repos