name: List MCBS Core Repos

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: Initialize Workflow
        uses: ./actions/init-workflow
        with:
          installGithubCli: true

      - name: List Repos
        shell: bash
        run: |
          for ((p=1;;p++)); do 
            o=$(gh api --method=GET orgs/freenet-group/teams/mcbs-core/repos --field=per_page=100 --field=page=$p | jq -r '.[].html_url');
            if [ -n "$o" ]; then 
              printf '%s\n' "$o"; 
            else 
              break;
            fi;
          done
        env:
          GH_TOKEN: ${{ env.TOKEN }}
