name: List MCBS Core Repos

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - name: Github CLI installieren
        uses: freenet-actions/setup-github-cli@v2