name: List MCBS Core Repos

on:
  workflow_dispatch:

jobs:
  list-repos:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - id: read-aws-secrets
        name: Read AWS Secrets
        uses: ./actions/read-aws-secrets
        with:
          awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
          awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          awsParameterPairs: |
            /github/secrets/mcbs_token = TOKEN

      - name: Initialize Workflow
        uses: ./actions/init-workflow
        with:
          installGithubCli: true
          installJq: true

      - name: List Repos
        shell: bash
        run: |
          gh api \
            -H "Accept: application/vnd.github+json" \
            -X GET /orgs/freenet-group/teams/mcbs-core/repos \
            -F "per_page=50" > data.json
          jq '.[].html_url' data.json
        env:
          GH_TOKEN: ${{ env.TOKEN }}

      - name: List Repos II
        shell: bash
        run: |
          gh api graphql --paginate -f query='
            query {
              organization(login: "freenet-group") {
                team(slug:"mcbs-core"){
                  name
                  repositories(first:3){
                    nodes { url }
                  }
                }
              }
            }'

#            query($endCursor: String) {
#              viewer {
#                repositories(owner: "freenet-group/mcbs-core", first: 100, after: $endCursor) {
#                  nodes { url }
#                  pageInfo {
#                    hasNextPage
#                    endCursor
#                  }
#                }
#              }
#            }'
        env:
          GH_TOKEN: ${{ env.TOKEN }}
